### ISSUE TITLE
OSS - Reorganize tasks

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#100]
From @gcharest:
Need to breakout in buckets: Using, Contributing and Publishing.
IP COE has already well established rules around publishing: DG approval required for all OSS licences and even to Public Domain.

Goes the same way for contributing: DG approval required but there's work in place to have an "automated" form for approving an employee to contribute to it.

Finally, using OSS should be broken down in whether we're using as COTS or as part of development project to help with the compliance.

**Comment by smellems** [comment]
Using: the EA way forward seems to includes consideration (prioritization?) of OSS.  We should follow and contribute!

Glad to hear there is already some processes in place for publishing and contributing.  Let's work on making it easier for developers!

**Comment by jaysonmc** [comment]
Is this actively being worked on, or does this go back into to-do?

**Comment by gabrielcossette** [comment]
Agreed, moved to ToDo for now.
