### ISSUE TITLE
Presentation about OSS Licensing and IP

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1018]
Do a presentation to inform ***non-technical*** audience regarding the licensing and intellectual property model of OSS

This to:
- help inform and educate procurement
- help inform and educate legal

Context: procurement can involve getting into a contract. Getting into a contract limits our ability to pay via credit cards, acquisition cards, or other digital means. Getting into a contract is required if there is security or IP-related aspect to the work.

**Comment by jaysonmc** [comment]
- IITB Showcase
- MTLC MLTC ... whatever

- SLF

**Comment by smellems** [comment]
Presentation for the team scheduled October 7th
