### ISSUE TITLE
Business case for commitment from CFOB

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1029]
https://docs.google.com/document/d/1dpsXvXY_iHsgJAAPQzrX8gOhm5ttC_JCCGZKvWRWQZk/edit

from notes in https://etherpad.wikimedia.org/p/iitbs-gcd3v3x

**Comment by remyb2canada** [comment]
https://docs.google.com/document/d/1Y0PI_sfNPkQ3xG2T_9LVYNAPp3BR4PPj3vCdvQaeeIU/edit

**Comment by jaysonmc** [comment]
@RachelMuston this is in progress now, yes?

**Comment by RachelMuston** [comment]
https://docs.google.com/document/d/1dpsXvXY_iHsgJAAPQzrX8gOhm5ttC_JCCGZKvWRWQZk/edit?usp=sharing

**Comment by RachelMuston** [comment]
This is currently with CFOB Innovation team for review (sent Aug. 25)

**Comment by smellems** [comment]
Meeting for comments Sept 23rd.

**Comment by RachelMuston** [comment]
This issue has been broken out into sprint-sized chunks.
