### ISSUE TITLE
Update Strategies/WebServicesAccess.md

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#103]
Update [WebServicesAccess.md](https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/web-services-access.md) to ... 

- [ ] Follow-up if "Evaluation of impact of compliance with TBS PIN" has been done (see deck)
- [ ] Directly relate to business value
- [ ] Reference DLP project 
- [ ] Reference TBSs solution
- [ ] Suggest steps 
  1. Implement DLP
  2. Open applications collaboration applications

**Comment by jaysonmc** [comment]
@smellems Is this actively being worked on, or back into to-do?

**Comment by gcharest** [comment]
@smellems Can we close?
