### ISSUE TITLE
Executive champion presentation

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1030]
Executive Champion presentation (the idea, business case / diagnosis, untapped potential - how many teams have $$ to spend but they don't because no easy way to do it, and they remain being overworked), the potentials (ESDC mandate, untapped potential), the efforts needed behind it / bureaucracy hacking)
 https://govmatters.tv/the-role-of-bureaucracy-hackers-in-government/

**Comment by jaysonmc** [comment]
Booked for June 19th
