### ISSUE TITLE
Check in with Unions/HR on LDV procurement (GCDevEx)

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1064]

**Comment by jaysonmc** [comment]
How to present to the committee

**Comment by jaysonmc** [comment]
Generic mailbox sent to @RachelMuston

**Comment by RachelMuston** [comment]
Holding on contacting the generic mailbox until we receive the comments on the business case from CFOB and we have more details on the process/design.

**Comment by smellems** [comment]
Not needed for pilot

**Comment by RachelMuston** [comment]
Martin and Mathieu have had in camera meetings with the ESDC union reps. These discussions are ongoing.
