### ISSUE TITLE
Look into private sector companies who provide procurement of services

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1066]
Mathieu gave the example of a company in QC that allows you to enter your requirements online (e.g. I need a room that is 12x12 tiled) and then companies bid. 

Does anyone know the name of this company or similar?

I know of upwork: https://www.upwork.com/

Also I know that 18F's mico-procurement platform functioned in this way - folks bid amounts (lowest bidder won)

**Comment by RachelMuston** [comment]
Other examples: https://wwww.goquotes.ca. (construction gigs), https://hackerone.com/bug-bounty-programs

**Comment by RachelMuston** [comment]
Need to determine exactly what the ask is here....is it to learn about and document different operating models and best practices?

**Comment by smellems** [comment]
related #1063

**Comment by RachelMuston** [comment]
Research compiled here: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/3rd%20party%20procurement%20services_research.docx?d=wb4679b9843c14b80b7cc608e550cbe83&csf=1&web=1&e=Wl3aXb
