### ISSUE TITLE
ESDC IP COE meeting

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1067]

**Comment by jaysonmc** [comment]
Asked director. Looking for contact info

**Comment by jaysonmc** [comment]
Ask director to follow up with DG if nothing by July 13th

**Comment by jaysonmc** [comment]
@jaysonmc to follow up

**Comment by jaysonmc** [comment]
Followed up. Discussions in progress among senior management regarding outreach

**Comment by jaysonmc** [comment]
Follow up

**Comment by jaysonmc** [comment]
@gabrielcossette to contact IP COE

**Comment by RachelMuston** [comment]
Meeting scheduled for Thursday Aug. 13.  Questions we have for the team are here: https://mensuel.framapad.org/p/dx2imdmdzg-9i97?lang=en

Note: IP COE team falls under the same director as the Procurement Innovation team

**Comment by jaysonmc** [comment]
@RachelMuston move to done?
