### ISSUE TITLE
Save self-assessment results

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1105]
Azure Sandbox for temporary solution

**Comment by smellems** [comment]
- To know if it's being used
- To have data to identify areas to improve

Need a way to identify if users are from ESDC or IITB.

**Comment by smellems** [comment]
Related to/same as https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/issues/14

**Comment by gcharest** [comment]
https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/tree/submit-data-function introduced the ability to call the Azure Function.

Further work/research required to confirm implementation: security, privacy, etc.

**Comment by gcharest** [comment]
Will be closed by https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/pull/50
