### ISSUE TITLE
Section 2 (Process): Create questions for assessment

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1111]
Based on https://github.com/sara-sabr/ITStrategy/issues/1102, create questions for the survey

- Questions
- Answers
- Weighting (Ex: Answer A on this question is worth x points, while answering b on this question is worth y points, etc...)

**Comment by jaysonmc** [comment]
PR pending ...

**Comment by myp192** [comment]
PR #1200
