### ISSUE TITLE
Blog: What companies to follow

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1116]
Depts often look to banks, or insurance companies, or other governments to learn from -- which isn't the best approach. Project to Product (~pg 187 on Kindle) & Gene Kims podcast (episode 2 & 3) discuss the idea that each "revolution" (ex: industrial) follows the same pattern. Some companies learn how best to leverage the new technology and become hugely successful. Then companies learn from these successes, and begin implementing the lessons of the success stories (the distribution phase, or some such thing). Companies that do not learn from the vangaurd companies fail.

Conclusion: We should be learning from those who have mastered the new technologies, not looking to other companies struggling to keep up to generate/derive our own direction

**Comment by remyb2canada** [comment]
Contact @jaysonmc to see if his new TBS team has a strategy website/kanban to either:
a) move this item to their kandban
b) keep it, but ask for guest post

**Comment by jaysonmc** [comment]
Hmm, nope. No kanban board I can move it to. But, happy to invest some time in writing it if folks are interested. 

Your call of course. The issue lives on your board. Keep or delete. Whatever works for you works for me.
