### ISSUE TITLE
Publish GCcode Strategy v1

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1125]
Presentation asked the IITB adopt GCcode (as hosted by SSC) as the official solution for source control to share within the GC.

**Comment by jaysonmc** [comment]
I signed off VPN for the day, but Ill do this tomorrow am

**Comment by gabrielcossette** [comment]
@jaysonmc No need, I already sent them the draft GCcode strategy for comment :) Sorry, I should have picked the issue beforehand.
