### ISSUE TITLE
Define outreach

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1127]
Who are we reaching out to and why?
- Other departments
- Other branches?
    - How should we reach out?

**Comment by gcharest** [comment]
Starting point is here: https://014gc.sharepoint.com/:x:/r/sites/strategyBuildvsBuy/Shared%20Documents/stakeholders-engagement.xlsx?d=w1753b0a3acae41a3bc1e78c37fb6164e&csf=1&web=1&e=I6a3Ks

**Comment by jaysonmc** [comment]
I reached out to our mgmt to contact legal

@gcharest, have you reached out informally to finance? If yes, we can close this issue?
