### ISSUE TITLE
Add measurement section

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1130]
What is the outcome of the strategy? What are we measuring?

For example: 

- Increase the adoption of open source
  - In line with with TBS direction (Ex: Digital Standards) and increased open source usage is correlated with higher IT performance

**Comment by gcharest** [comment]
Adoption/Building
- Increase contributions to third party OSS
- Decrease of forked versions of OSS with unaligned upstream/without contributions

Buy
- Decrease lock-in situations (how do measure that? maybe propose to APM lock-in field?)
- Increase transfer of system runtime to third party Cloud service providers
