### ISSUE TITLE
Update content (internal SharePoint): SDM

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1134]

**Comment by jaysonmc** [comment]
@myp192 
Did we do this last week?

**Comment by gabrielcossette** [comment]
Not sure if this issue is related to this but all the material was moved to Office 365 and links in the internal SharePoint have been updated.

**Comment by gabrielcossette** [comment]
Forget my previous comment, I understand what it means now. I'll work with @myp192 on this.
