### ISSUE TITLE
Add order of preference into Build vs Buy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1136]
*Core to mandate*

1. Adopt
2. Adopt and Build
3. Build
5. Buy
4. Adopt and Buy
6. Adopt, Buy and Build
7. Buy and Build

*Not core to mandate*

1. Adopt
2. Adopt and Buy
3. Adopt and Build
4. Adopt, Buy and Build
5. Buy
6. Buy and Build
7. Build

Should also emphasize need to measure and track the compliance with this order of preference 
Add proposal to mention (Ex: adopt should increase, buy should decrease). Linked to https://github.com/sara-sabr/ITStrategy/issues/1137

**Comment by gcharest** [comment]
Order of preference when: Core to mandate and Complex

We do want to minimize the amount of custom maintenance internally but we also want to increase our ability to push changes upstream of the core version (OSS allows for this whereas changing features in a COTS is unlikely)

**Comment by jaysonmc** [comment]
@gcharest Does this still apply, or is it taken care of by the measurement section (https://github.com/sara-sabr/ITStrategy/issues/1130) ?
