### ISSUE TITLE
Add Coherent Action for measuring outcomes

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1137]
A coherent action to create a tool that begins an automated approval process for a given tool

- Record recommendation of tool (adopt/build/buy (or further nuance))
- Record if EA changes recommendation
- Record what final decision was

**Comment by gcharest** [comment]
- Automated progress tracking/strategy success measurement

**Comment by gcharest** [comment]
Coherent set of actions:
- Establish the current key metrics baseline and measure on-going progress

I believe that the concept of automating this progress tracking should be part of the continuous improvement Strategy based on our chat @jaysonmc @gabrielcossette @smellems ?

**Comment by jaysonmc** [comment]
@gcharest There is overlap. Though each strategy, I would argue, should be self contained. That is, the creation of a process to measure the outcomes of a given strategy should be outlined in each strategy, as it is a 'coherent action' that needs to be taken for the implementation of the strategy to be a success.

Granted, it still has links with the Continuous Learning Strategy, where I would propose we put in place a more general framework for the entire department to measure and report on their metrics (upon which they continually improve)

Thoughts?
