### ISSUE TITLE
Adjust definitions

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1139]
Proposed alternate definitions following the creation of https://github.com/sara-sabr/ITStrategy/issues/1138

Adopt: IITB provides any level of support; or users/devs self support. Light configuration only. No customization.

Buy: ESDC pays (exchange of $) for a solution, software or service as well as for development or support from outside ESDC (or GC?)

Build:  ESDC, GC or third party configures, assembles or develops/customizes a solution, software or service

**Comment by Moro-Code** [comment]
By this definition are we classifying MSDynamics, O365 ect as build ?

**Comment by gcharest** [comment]
|IT Solution | Adopt | Buy | Build |
|---|---|---|---|
| IT Product already exist | Yes | Yes | Depends |
| Architecture | Internal | External | Internal |
| Configurable | Yes | Yes | Depends |
| Customized code | No | No | Yes |
| Exchange of money | No | Yes | Depends |
| Influence on IT Product roadmap | Depends | Limited | High |

**Comment by gcharest** [comment]
Adopt: Commoditized product/Solution, whether OSS, COTS, XaaS
Buy: Services and goods - Rights to use, training, material, warranties, etc.
Build: Customized code/product for specific needs, whether bought or developed internally.

Overall lifecycle of IT solution: Architecture, dev, deployment, support, etc. may be a combination of all of the above.
