### ISSUE TITLE
Create DevOps Maturity Assessment

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#115]
Identify 15 pieces needed for DevOps within an organization

**Comment by jaysonmc** [comment]
@gabrielcossette Where did 15 pieces come from? Feel like I'm missing a reference ...

**Comment by gabrielcossette** [comment]
> 
> 
> @gabrielcossette Where did 15 pieces come from? Feel like I'm missing a reference ...

@jaysonmc It comes from the Trello card.

**Comment by gcharest** [comment]
I'm not clear either on what we mean hear. Should we focus on DORA instead?

related to merged PR #78
