### ISSUE TITLE
Document bilingual license translation issues

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1168]
Meeting with PSPC legal team to discuss having MIT license translated to be used with DevX

**Comment by gcharest** [comment]
Will need to flesh out the desired outcome/scenario. E.g.:

The intent of this opportunity is to achieve X functionality.
The code will be an extension of the 3rd party project Y, licenced under MIT, so the opportunity's work will need to be released under the same terms and conditions.

Choice: 
- accept the MIT terms and conditions
- transfer IP to Crown; we apply the licence ourselves.

**Comment by jaysonmc** [comment]
Based on thread between IT Strategy and TBS (CDS) & DND, document conclusions

**Comment by RachelMuston** [comment]
The info shared on the above mentioned thread has been documented on our sharepoint site here: https://dialogue/grp/BU6810070/Content/DevX/Notes%20on%20OSS%20licence%20translation.docx.  This document is also on the GCDevEx O365 ShrarePoint site.
