### ISSUE TITLE
Make Venn diagram reflect the predominance of permutations.

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#1176]
Since we say above that obtaining an IT solution is almost never just a build, just a buy or just an adopt, should those areas of the Venn diagram be smaller to reflect that?

_Originally posted by @RachelMuston in https://github.com/sara-sabr/ITStrategy/pull/1121_

**Comment by jaysonmc** [comment]
@gcharest @smellems I think this is in progress?

**Comment by smellems** [comment]
![image](https://user-images.githubusercontent.com/2353299/94020637-25805f80-fd81-11ea-9842-7f7f65c0b476.png)

Maybe for later..
