### ISSUE TITLE
Create a status update deck for GCDevEx

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1186]
Deck will be used at the next meeting with Martin, Julie and Mathieu.

To include details on the work with CFOB, mental MVP, resources required, costs.

**Comment by smellems** [comment]
DG Comm presentation..
https://sara-sabr.github.io/ITStrategy/presentation.html?markdown=en/2020-GCDevEx-DG-Comm.md

**Comment by RachelMuston** [comment]
Status update deck for Mathieu not needed for now
