### ISSUE TITLE
Onboard ESDC in the GC Workplace pilot

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#119]

**Comment by gabrielcossette** [comment]
Questions from @gcharest:
> @jaysonmc  Is this the one where we discuss what needs to be done to be 100% mobile workers?

**Comment by gcharest** [comment]
I think this was the GC Workplace pilot, some sort of Workspace 3.0 where any employee of the GC can come in the common space offices. Need to be part of the pilot though.

**Comment by gabrielcossette** [comment]
@gcharest Here's the pilot information, but ESDC isn't part of it unfortunately: http://www.gcpedia.gc.ca/wiki/GCcoworking

**Comment by gcharest** [comment]
Do we want to explore GC Workplace for ESDC? @jaysonmc @remyb2canada  @smellems @gabrielcossette 

Low priority IMHO.
