### ISSUE TITLE
Lead time analysis

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#120]
- [ ] Email Project Management Office, Briere, Sonia S [NC] <sonia.briere@hrsdc-rhdcc.gc.ca>
- [ ] Identify two development projects to use
- [ ] Identify time from PBI to Production
- [ ] How long, on average, do items stay as PBIs?
- [ ] How long do items spend in QA?
- [ ] How long do items spend in security?
- [ ] How long do items spend with Ops?

**Comment by gcharest** [comment]
Lead time analysis would probably be done on multiple processes/value streams.

We'd need to pick and choose one to start.
