### ISSUE TITLE
Create a spreadsheet on directors interview questions for responses

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#1212]

**Comment by myp192** [comment]
Mention : We wanted to encourage a safe space (psychological safety) with the IITB Stakeholders interviews to get the best use of collecting their perspectives. 

We discussed the interview being pen and paper only (Interviewees package) - having all the answers confidential and not have names and teams associated to any answers in our notes.

This will help us lead to the "What we heard" report.

**Comment by philipe-girard** [comment]
Reviewed by Phil.  Might require more update after team meeting.
