### ISSUE TITLE
Adapt deck with clear recommendations/decisions points

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1224]
Last slide should include target groups for actions.

Add slide with consulted parties

**Comment by gcharest** [comment]
https://014gc.sharepoint.com/:p:/r/sites/strategyBuildvsBuy/Shared%20Documents/Adopt%20Buy%20Build%20Strategy%20-%20DG%20Comm.pptx?d=w409da077c22b43f09379d3ec30a22c9a&csf=1&web=1&e=hFcFPo
