### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#123]
https://twitter.com/AlexBenay/status/1138429374145998849

Need to:
- investigate applicability of blockchain at ESDC (with SSPB Service Research / Clara Morgan)
- investigate added value of private blochain over private database

- [ ] Contact Talent Cloud (who is using blockchain)
- [ ] Get update on progress for ESDCs blockchain research (Sean Midford)
- [ ] Brief Team

**Comment by gabrielcossette** [comment]
Updates from @remyb2canada:
- Lead for blockerts des Free Agents est Valérie Thomas avec Talent Cloud. Ils utilisent Ethereum
https://www.blockcerts.org
https://blockcerts.talent.canada.ca
- Meeting with IITB R&D and SSPB Service Research (Clara Morgan).

**Comment by remyb2canada** [comment]
Updates
Service Research reached out to Free Agents and are planning a demo/technical discussion on the subject with IITB

**Comment by gcharest** [comment]
We're going to be involved in the roundtables. Need a volunteer to attend for the team.

@jaysonmc @gabrielcossette @remyb2canada @smellems
