### ISSUE TITLE
Knowledge transfer to Target SDM delivery team (DevOps CoE)

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1230]
- Financial model : #901

**Comment by remyb2canada** [comment]
If we add DevOps CoE in the CIOEC presentation, we should treat this issue as closed

**Comment by remyb2canada** [comment]
Should be done once we:
1. Nail down the Product Management framework (replacing the Agile Governance Framework)
2. Do the DGCOMM presentation
