### ISSUE TITLE
TSDM Presentation to DGCOM

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1232]
2021-01-28
this links with issue #1437 

The TSDM will most likely require some changes due to the gap between software and data (i.e. the TSDM needs to acknowledge that data is the asset, and it is not owned by software; it is owned by the organization).

This would require feedbacks by DAS and CDO, update the TSDM, and reflect on whether an action (ask) as part of the CIOEC deck on this topic is required.

**Comment by remyb2canada** [comment]
Putting this back in backlog. 
Issue #1437 needs to be completed first as it will inform the content of the CIOEC deck, and most likely some changes in the TSDM strategy's architecture section (i.e. relationship between data and software)

**Comment by remyb2canada** [comment]
renamed to presentation to DGCOMM

**Comment by remyb2canada** [comment]
This presentation will most likely change to one that asks for two things:
1. Inform of the DevOps CoE creation and its ongoing work with other IITB teams (lead by IITB Innovation Team)
2. Inform of work on a Business Case for a Product Management Framework (lead by IT Strategy)

This would scrap the idea of a "Agile Governance Framework" in favour of just a Product Management one. Product teams are free to chose which governance framework they want as long as it aligns to the Product Management's expectations.
