### ISSUE TITLE
Identify how Strategies should be built to support DevOps

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#125]
Revise and contribute to 

https://github.com/esdc-edsc/Welcome/blob/master/Recommendations/DevOps_SDLC.md

Investigate with Laughland, Shaun S (shaun.laughland@hrsdc-rhdcc.gc.ca)

There is also an initiative by the PMO. See in our onenote the reference to DevSecOps SDLC documentation:
`onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/References.one#ESDC%20Specific%20References&section-id={F01B1215-51E3-4CC0-B39A-B3CBACE5EC64}&page-id={FA9FED31-51F5-4984-A885-506F668E5A0E}&end`

**Comment by gcharest** [comment]
Related to #124

**Comment by gcharest** [comment]
To link Google DevOps Capabilities as well.
