### ISSUE TITLE
Iterate (Work on usability issues ) UX

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#1253]

**Comment by smellems** [comment]
Disable btn-default style when active - https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/commit/c86962a3a91f47fa59478a6526749ec81894b4af

Switch disagree and agree, fix French - https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/commit/ae517729dd8775e35a3b428aea0e862126d54d25

Make section title and score bigger, cleanup h styles - https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/commit/612583de8287df32b0b4ec5c71fa432cd1c12a5a

Fix score calculation on results page - https://github.com/sara-sabr/auto-evaluation-devops-self-assessment/commit/921dd9cb2fc5d1eed6749acca0221e87164a4587
