### ISSUE TITLE
update the Teams page to reflect HR changes

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1256]
https://sara-sabr.github.io/ITStrategy/team.html
https://sara-sabr.github.io/ITStrategy/lequipe.html

**Comment by myp192** [comment]
Remove My from the team page as of Feb 4th :(

**Comment by smellems** [comment]
fix Phil's picture

**Comment by philipe-girard** [comment]
G: Would it please be possible to change the image ratio on my picture?


Thanks.


Phil

________________________________

**Comment by philipe-girard** [comment]
A PR is done already :)

--
Guillaume Charest

Conseiller, Direction générale de l'innovation, de l'information et de la technologie
Emploi et Développement social Canada / Gouvernement du Canada
***@***.******@***.***> / Tél. : 819-639-8884

Advisor, Innovation, Information and Technology Branch
Employment and Social Development Canada / Government of Canada
***@***.******@***.***> / Tel: 819-639-8884
