### ISSUE TITLE
Review/Document Software Approval Process

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#126]
- [x] Meeting booked for July 9th with Betty-Anne (and Shaun L.)
- [x] Research current process
- [x] Provide findings to team
- [x] Process on [ITSM Sharepoint here](http://dialogue/grp/PMS-SMP/SitePages/Business-Processes.aspx)

**Comment by gcharest** [comment]
Was the meeting successful? What was the outcome? @gabrielcossette

**Comment by gabrielcossette** [comment]
It's actually assigned to @jaysonmc. Any updates?

**Comment by jaysonmc** [comment]
Review of documents can be found here 

onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Notes.one#Summaries%20&section-id={8F7042FC-8CA2-4132-A942-B030364A6FE4}&page-id={E2000786-99AD-436F-9145-A2E309FE0FA7}&end
