### ISSUE TITLE
GC/Code Official Support Pitch

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#130]
https://github.com/gcdevops/strategie-devops-strategy/blob/master/Content/OfficialGCCodeSupport.md

- [x] Consult with community
- [x] Send to Martin
- [x] Investigate cost recovery model
- [x] Jayson to review
- [x] Create elevator pitch to ADM (cost recovery model?)
- [x] Submit to Martin
- [x] Document relevant benefits for existing projects (e.g. OAS)
- [x] @gabrielcossette Prepare presentation for Architecture committee
- [ ] Determine Value Add for CDO and contact them for feedback
- [ ] Add costing estimates
- [ ] Waiting for response from Martin

**Comment by jaysonmc** [comment]
https://github.com/gcdevops/strategie-devops-strategy/pull/23
