### ISSUE TITLE
Ask HR advisor about using jobs.gc.ca

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1319]

**Comment by remyb2canada** [comment]
e.g. create a "micro-procurement" channel on jobs.gc.ca, posted for 1 year, and link to the individual work task. Doing this we could mine demographic data.

**Comment by smellems** [comment]
Response from HR was that we can't use GCjobs because our opportunities are not "jobs".

We will most likely use email to receive applications
