### ISSUE TITLE
Review Innovation Programs at ESDC and how they relate to each other

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#132]
Establish value chain of innovation activities throughout ESDC

**ESDC Innovation Programs**

- Innovation Lab (under the the Strategic and Service Policy Branch)
- Innovation Framework (under IITB)
- Grassroot Innovation program (by IITB Enterprise Architecture)
- Research & Development (R&D) team under Simon Gascon
- [Innovation landscape map at ESCD](http://dialogue/grp/BU6810070/Shared%20Documents/Reference%20Materials/InnovationLab_ESDCinnovationMap_V10.pdf)

Need to review how they relate to each other and how the IT Strategy can capitalize on them.

**Resources**

- [Deloitte's 10 types of innovation](https://blog.hypeinnovation.com/using-the-ten-types-of-innovation-framework)
- [Harvard Business Review's You Need an Innovation Strategy](http://dialogue/grp/BU6810070/Shared%20Documents/Reference%20Materials/HBR_You%20need%20an%20innovation%20strategy.pdf)
- [Minor Projects here](http://dialogue/grp/EDSC-LAB-ESDC/Innovation%20Lab%20Pics/Webpages/Questions/LAB_JourneyofaLabMACROProject_V1.pdf)
- [Major Projects here](http://dialogue/grp/EDSC-LAB-ESDC/Innovation%20Lab%20Pics/Webpages/Questions/LAB_JourneyofaLabMACROProject_V1.pdf)

**Intelligence Gathering**
- [x] Review Innovation Lab's onboarding process
- [ ] Review Innovation Lab's fit within the ESDC departmental planning and project onboarding
- [ ] Review IITB Innovation Framework's onboarding process
- [ ] Review IITB Innovation Framework's fit within the IITB project onboarding
- [x] Review Grassroot Innovation Program by IITB EA
- [ ] Review Grassroot Innovation Program Website (@gabrielcossette & @jaysonmc)
- [ ] Review Grassroot Innovation Program's fit within the IITB project onboarding process
- [ ] Should they work together? Why, why not? If yes, then how?
- [ ] Create 'deck' using reveal.js

**Comment by jaysonmc** [comment]
On a ce document aussi ... Je pense que c'est lié? 

https://github.com/sara-sabr/ITStrategy/blob/master/drawio/en/GovernanceValueChain.drawio
