### ISSUE TITLE
EARB definitions of IT Solutions, Products, etc. and breakdown of rights vs services.

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#1332]
Question
At Governance / Produce the EARB standard definition of IT Solutions. Do we mean to formally define the relationships between IT Solutions, IT Products, Software, Infrastructure?

i.e. What is in Appendix A - Business Case / Build vs Buy : Oversimplified Question

_Originally posted by @remyb2canada in https://github.com/sara-sabr/ITStrategy/pull/1325#discussion_r513708824_

**Comment by gcharest** [comment]
Need a more nuanced understanding of the complexity of managing IT within the organization. Bundling everything in procurement process seems like a simpler way of managing things from in incoming point of view but creates medium to long term constraints that could hinder ability for the org to course correct and actually deliver on its mandate.

**Comment by smellems** [comment]
Action item added to strategy and approved at ARC.
