### ISSUE TITLE
Finalize Mandate

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#134]
- [x] Meet on June 12th to compare individual mandates
- [x] Write up final mandate
- [x] Review final mandate
- [x] Submit final mandate to Martin
- [x] Refine dual purpose mandate

**Comment by gabrielcossette** [comment]
From @remyb2canada:
@jaysonmc @gcharest, what is "dual purpose mandate"?

**Comment by remyb2canada** [comment]
@jaysonmc what is "refine dual purpose mandate"?
Should we also add "submit final mandate to DS"?

**Comment by gcharest** [comment]
Need to go at DG committee.

**Comment by gcharest** [comment]
See #279 for final items to close.
