### ISSUE TITLE
Research billingual git repo

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1341]

**Comment by smellems** [comment]
One found be @gabrielcossette that might be good enough
https://codeberg.org/?lang=fr-FR

**Comment by smellems** [comment]
Clients and Suppliers can choose to use source code repo of their choice.
Gitlab will be recommended (multilingual) for teams that don't already have work on Github or others.

Supplier can work on Client's repo or choose other and send link to branch by email.
Supplier could also work locally and send branch or patch by email.
