### ISSUE TITLE
Document personas for micro-procurement pilot

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1349]
- Supplier personas could be: supplier that is a student, supplier that is a freelancer, small company, medium company
- Client personas could be: Client from IITB, client from ESDC, client from Service Canada

**Comment by ElminaIusifova** [comment]
Here is the [Link to Sharepoint ](https://014gc.sharepoint.com/sites/GCDevEx/Shared%20Documents/Forms/AllItems.aspx?viewid=66d91ce5-39ab-4590-90b1-2ecc9f8981e6&id=%2Fsites%2FGCDevEx%2FShared%20Documents%2FPersonas)
