### ISSUE TITLE
Create a template invoice for suppliers to use

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1433]
For suppliers to use for micro-acquisition. Work with IITB FPS to understand what information needs to be in the invoice.

Email sent to FPS on Jan. 5 asking about information that must be included in invoices. They are away until Jan. 11.

FPS still away. We will create low fidelity template for now (list of fields that would be in an invoice) and if we can't validate before, we will validate during the Feb workshop.

**Comment by myp192** [comment]
Template is in sharepoint. However, will also be reviewed in workshop

**Comment by RachelMuston** [comment]
Fields that need to be in the template is in this document: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Workshops/Process%20workshop/Artifacts/Artifact%20N%20-%20template%20invoice.docx?d=w7df36df62bf84375be1330483e22eed6&csf=1&web=1&e=58p21J

**Comment by RachelMuston** [comment]
Draft template sent to FPS on April 22 for their review.

**Comment by RachelMuston** [comment]
Invoice template is now available on the website.
