### ISSUE TITLE
Translate and send out invitation for the micro-acquisition design workshop

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1446]
**English follows**

Cet atelier fait partie de la phase de conception du [pilote de micro-acquisition](https://sara-sabr.github.io/ITStrategy/pilote-de-micro-acquisition.html). Vous avez été invité à cet atelier car vous avez été identifié comme un partie prenante avec des rôles et responsabilités définis dans le futur processus de micro-acquisition et/ou dans la conception de ce processus. 

Au cours de cet atelier de 2 heures, nous passerons en revue l’ébauche du processus de micro-acquisition, en utilisant des scénarios, des personas et des ébauche d'artéfacts. L'objectif de cet atelier est de découvrir tout ce à quoi nous n'aurions pas pensé ou pris en compte lors de la conception des différents artéfacts, ainsi que de trouver de possibles lacunes/défis qui doivent être résolus.

Si vous n'êtes pas disponible pour participer à ce moment, veuillez nous en informer dès que possible afin que nous puissions reporter la date.

Plus près de la date de l'atelier, nous partagerons les documents nécessaires.

Merci d'avance de votre participation et contribution pour nous aider à réduire les risques de ce processus !

--

This workshop is part of the design phase for the [micro-acquisition pilot](https://sara-sabr.github.io/ITStrategy/micro-acquisition-pilot.html). You have been invited to this workshop as you were identified as a key stakeholder with defined roles and responsibilities within the upcoming micro-acquisition process and/or design process. 

During this 2 hour workshop we will step through the draft micro-acquisition process, using scenarios, personas and draft artifacts. The goal of this workshop is to uncover anything we haven’t thought of or accounted for in the draft design of the various artifacts, as well as find possible faults/challenges that need to be addressed.

If you are not available to attend at this time, please advise as soon as possible so that we can reschedule. 

Closer to the date of the workshop we will be sharing required materials.

Thanks in advance for your participation and input to help us de-risk this process!

Rachel

**Comment by RachelMuston** [comment]
Hi @gabrielcossette, @gcharest, @smellems, @remyb2canada , @myp192! Wondering if anyone has time to do a quick review of the french for the invitation email for the workshop?  Text is in the above comment.

**Comment by gabrielcossette** [comment]
Looks good, just did some minor adjustments by editing the issue's description above.

**Comment by RachelMuston** [comment]
Merci @gabrielcossette!
