### ISSUE TITLE
Redundancy in Main menu and Our Documents tab

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#1452]
1. Vision content appears under the Vision tab and in Our Documents (redundant)
- Remove Vision from Our Documents

2. Strategies content appear Strategies tab and in Our Documents tab (redundant)
- Remove Strategies from Our Documents

<img width="1448" alt="Screen Shot 2021-01-12 at 12 51 47 PM" src="https://user-images.githubusercontent.com/32398063/104352873-37734300-54d5-11eb-95e8-0aa6905ea431.png">

**Comment by smellems** [comment]
Fixed in #1511
