### ISSUE TITLE
Remove draft mentions on site pages

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#148]
@jaysonmc @smellems @gabrielcossette @arushisharma19 @remyb2canada 

Proposing we remove the DRAFT mention on page titles since we added a notice across the site.

Also, proposing we move the notice at the bottom of the page?

**Comment by remyb2canada** [comment]
agreed that we could remove "DRAFT" from all pages.
But we should have an indication of the maturity level of the page/document. I.e. a category of:
- work in progress
- in peer review
- approved

What may be challenging is that if we have an approved doc (e.g. StrategyRoadmap) but that we then start making changes to it. Would we then have an "approved" version and a "work in progress" version? I guess at that stage, if a page is "approved" that means any modifications to it must be done in a separate branch and that branch gets approved accordingly (not just by the team but also by the governance bodies)

**Comment by gcharest** [comment]
Related to #213

Duplicate
