### ISSUE TITLE
Review the IITB Way Forward and highlight areas to be involved

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#150]
- [ ] review the [IITB Way Forward](http://dialogue/grp/IITB-DGIIT-Gov-New-Nouveau/Documents/Departmental%20IMIT%20Plan/19-20%20Plans/IITB%20Moving%20Forward%20v2.docx)
- [ ] identify areas of priority that needs to be addressed from a strategic sense (e.g. IM, policy reviews, cyber security)

These areas will either be enablers or inhibitors to our [Strategy Roadmap](https://sara-sabr.github.io/ITStrategy/strategy-summary.html)

**Comment by gcharest** [comment]
Might be an Opportunity to link into our IT Picture documents.
