### ISSUE TITLE
Establish the Governance Value Chain map

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#151]
the IT value chain needs to be better established and understood at a high level. 
The value chain should adequately represent the series of activities that the organization (ESDC as a whole) performs to deliver IT products in alignment with its business vision. 

Refer to [this drawio diagram](https://github.com/sara-sabr/ITStrategy/blob/master/wip-tec/en/GovernanceValueChain.drawio)

- [x] Produce draft diagram
- [x] peer review with Finance and PMO. Debrief in [OneNote](http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/People.one#IT%20Value%20Chain%20Feedback&section-id={643E710D-A4B6-44C6-960A-4CC499129B6D}&page-id={FF91E512-56EF-4028-8E70-DF08708F67A5}&end)
- [ ] peer review with senior management (DS, AG)

**Comment by jaysonmc** [comment]
Moved back 'to-do' as meeting with PMs has been postponed until mid September to review 

Also no associated milestone

**Comment by remyb2canada** [comment]
Peer review done and debrief in [OneNote](onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/People.one#IT%20Value%20Chain%20Feedback&section-id={643E710D-A4B6-44C6-960A-4CC499129B6D}&page-id={FF91E512-56EF-4028-8E70-DF08708F67A5}&end)

**Comment by remyb2canada** [comment]
closed as more analysis is needed (especially financial)
