### ISSUE TITLE
Are languages in the tech bricks?

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1513]

**Comment by gabrielcossette** [comment]
I can look into it, as I'm digging into the tech bricks for the automated testing tools.

**Comment by gabrielcossette** [comment]
Development Languages is a tech brick 🙂 Internal link [here](https://dialogue/grp/TAWS-ATST/Technology_Standards/Brick%20Repository/Development%20Languages.mht)
