### ISSUE TITLE
Look at who else is doing this (in the GC, other govs, best practices)

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#1515]
Regarding any existing software assessments sharing in GC or other public administrations. Also look for any best practices.

**Comment by RachelMuston** [comment]
Confirmed that some informal sharing is happening (eg. between CRA and ESDC). Confrmed that TBS has been looking at this for a while but it has ended up on the back burner due to lack of resources, prioritization.
