### ISSUE TITLE
Meet with the directors of the pillars

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#1518]
Having integrated their existing assessment process into the new collaborative method mockup.

**Comment by philipe-girard** [comment]
Plan for January with Daniel Desforges and Dominique

**Comment by RachelMuston** [comment]
Meetings with TA team happened at the end of Jan 2022. Further meetings planned with the directors of the other pillars - Security, Accessibility, Privacy.

**Comment by RachelMuston** [comment]
Need to set up meetings with the directors responsible for the pillars (once we are ok with the deck)

**Comment by RachelMuston** [comment]
Met with the directors for TA, Privacy and Accessibility on March 10, 2022. Will be meeting with the director for Security on March 17.
