### ISSUE TITLE
Create the Medium/Long Term vision pictures

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#158]
Current view of what we need to do:

- Establish a "picture" of what IITB/ESDC will be in medium/long term
- May use various "views" to help speak to the various audiences:
  - Citizens/Businesses
  - IITB internal employees
  - ESDC employees
  - Government Partners (internal and external)
  - Systems view
  - Etc.

Key stakeholders/contributors to engage:

- ESDC
  - SSPB
    - Policy Horizon
    - CDO
    - ISB (DSO)
    - Innovation Lab
  - TISMB
  - CSB
  - IITB
    - BRM
    - Enterprise Architecture - IITB but others as well
      - Business, Information, Application, Technology, Security, Privacy, Accessibility
  - All senior advisors and change agents

This should be done in the open so that anyone that can contribute should have the ability to do so. We do not know everyone in the organization so all contributions are welcome.

**Comment by jaysonmc** [comment]
Should we keep this as a giant bucket issue, or break this into more granular issues? 

For example, if you're working on a specific to-do, perhaps that should be it's own task? 

@gabrielcossette 
@smellems 
@arushisharma19

**Comment by gabrielcossette** [comment]
We could keep a single issue and add checkboxes with names in the description?

**Comment by jaysonmc** [comment]
This should be our top priority issue, so I'm going to close with one and create issues for each TO-DO we currently have in the document. 

Almost all (if not all) work in progress items should be for our medium & long term documents
