### ISSUE TITLE
Develop "Current State" 1 Pager

### ISSUE THREAD

**Issue by philipe-girard** [sara-sabr/ITStrategy#1601]
One pager illustration of steps and timelines associated with getting something approved.  Includes formal and informal committees for approvals and consultations, with approximate timelines.  Will be used to educate Dinesh and Peter on why the governance can impede the timeliness of approvals.  This will lead to the next steps within this process to suggest remedial actions both in terms structure and technology.

https://github.com/sara-sabr/vue-governance/

**Comment by gcharest** [comment]
Current version https://014gc.sharepoint.com/:p:/s/IITBStrategy/EQfCGKlN2xVHqHwv1U5eDMoB6Nj0yiWuLH5oZTXj4mcsHg?e=egmzRu

**Comment by gcharest** [comment]
Still evolving but recommend presenting a first glance to management.
