### ISSUE TITLE
Presentations on our website do not open in IE

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1628]
Is this a known issue or something we could fix?
When I click on this link to the MA presentation: https://sara-sabr.github.io/ITStrategy/presentation.html?markdown=en/2021-Micro-acquisition_for_approval.md
It "opens" as a pop out in a separate window, but I just get a blank IE screen.
Phil is getting the same.

**Comment by smellems** [comment]
The issue is only with IE 11.  Maybe we don't need to fix it since it works with Edge, Firefox and Chrome.
