### ISSUE TITLE
Team brainstorm

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1641]
- Strategy (policy and action)
- OSS CoE (program office)
- Use of open standards
- Using OSS
- Publishing open source code
- Contributing to OSS communities
- ..

**Comment by gcharest** [comment]
Program office: scope/roles and responsibilities/model, etc. should leverage [ToDo Group guides](https://todogroup.org/guides/)

**Comment by gcharest** [comment]
Strategy itself to leverage: https://ec.europa.eu/info/departments/informatics/open-source-software-strategy_en
