### ISSUE TITLE
Translate screens for creating a GitHub account

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1666]
Need this to meet OL requirements french suppliers that need to deliver code on GitHub repos and ESDC clients (for clients who want to open a PR on the Micro-Acquisition repo for their opportunity)

**Comment by RachelMuston** [comment]
Document created here:  https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/User%20documentation/Admin/rejoindre%20GitHub.docx?d=w90c507c08a854834b8f58877b34d41d5&csf=1&web=1&e=AULxtQ

Ready for review.

**Comment by gabrielcossette** [comment]
Linked to #1848.
