### ISSUE TITLE
Conduct UX testing

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#1712]
3 UX testings will be conducted on May 25th. The test plan is here https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/_layouts/15/Doc.aspx?sourcedoc=%7B11FAC4CD-84C7-4A88-8466-98A16075635E%7D&file=Test%20plan.docx&action=default&mobileredirect=true

**Comment by smellems** [comment]
related #1261
