### ISSUE TITLE
Future of EA

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#173]
(TODO: What does EAs role look like in 5 years? Sources and references [CDS or 18f, for example])

What will EAs role look like in 5 years? How will the rest of the organization see them in 5 years? 
- Example, CDS does not have EA. They assume these responsibilities lie with the devs. Is this approach feasible for us, given our size and scale? If so, how? If not, what should we do?

**Comment by gabrielcossette** [comment]
I'm not sure. In my view, EAs are more "generalists" than devs. They must cover the Business and IM architecture along with Technical.

In these organizations, are devs responsible for evaluating/choosing COTS/SaaS too?

**Comment by smellems** [comment]
Modern Architecture capabilities should focus on

- Use a loosely coupled architecture allowing teams to work independently to deliver value.
- Architect for empowered teams allowing them to choose the tools they work with.

This feels like what CDS might be doing.  They don't have an EA team, but someone must have decided at some point to host on the cloud, to use Docker and Kubernetes.  The GitOps (DevSecOps) CI/Cd pipelines..  those feel like EA decisions even without a formal EA team.

**Comment by gcharest** [comment]
Addressed in IT Picture
