### ISSUE TITLE
IT Picture - medium term

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#177]
Provide a ~5 year IT Vision for ESDC from different perspectives (audiences)
https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/it-picture-medium-term.md

**Changes to Docs**

- [x] Strong Culture of Learning -> @gabrielcossette 
- [ ] timeline expectation for OneGC (SignIn Canada), and evaluate how much ESDC will be aligned to it
- [ ] Sign In Canada should be in production
- [ ] Review stats on public cloud vs hybrid cloud. Cloud tech yes but no necessarily public. Also risks related to Freedom Act (formely Patriot Act). Political aspect could make our risk management change. - Cloud Smart
- [ ] How cybersecurity will evolve. With all recent data leaks. Citizen has control of his privacy and chooses what to share. (E.g. https://en.wikipedia.org/wiki/Solid_(web_decentralization_project))
- [ ] Also add hiring aspect - as in hire staff that are continually learning. Add automation elements (which jobs will be automated in the future).
- [ ] Review Capabilities (contributed by Sebastien) and see which one should be added to Vision documents.
- [ ] Add vision of modern collaboration tools and practices (e.g. Office 365, GCDOCS)

**To Do**

- [ ] (@remyb2canada) Talk with IM on maturity of information sharing and openess by default - where do they see it be?
- [ ] (@smellems) find ESDC rep at Channel Integration (Strategic)
- [ ] (@gabrielcossette) Check with SSC with their relationships with CSPs, on premise cloud technology, and CSP on premise services
- [ ] (@smellems) find who is ESDC`s Digital Channel Stewart (OneGC update PPT, slide 6)
- [ ] (@remyb2canada) Find interim Data Strategy (Theoretically due in Sept - Contact CDO?)
- [ ] (@remyb2canada) Reach out to Mathieu Leprohon to find an EA rep to collaborate
- [ ] Add external references (Gartner, Forrester, Deloitte, etc.)

**Comment by gcharest** [comment]
Link with #190
