### ISSUE TITLE
Review the french text for the 'you have not been selected' message

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1772]
French text can be found here: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Change%20Management/Comms/TR0291%20-%20Notification_text_FR.docx?d=w4c68e110573d44bda086ad223cf47662&csf=1&web=1&e=tj8Yup 

English text can be found here: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Change%20Management/Comms/TR0291%20-%20Notification_text_EN.docx?d=w4c876929c02f47f5a579dcbcf63f57e5&csf=1&web=1&e=ypu0Un

* Note this text uses Notify formatting for variable names and conditional content.

**Comment by gcharest** [comment]
Looks great! added a few little comments but nothing blocking. Great work!
