### ISSUE TITLE
Pinned tweet for the MA twitter accounts

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1774]
- [x]  draft english
- [x] translate
- [x] Review translation (and ensure translation is under the Twitter character limit
- [x] post pinned tweet in en and fr

(character count does not include URL)

Current draft english (201 chars): "Want to get paid for writing #opensource code? Check out the opportunities on the micro-acquisition website. Simple application process, no security clearance needed, get paid by credit card or Paypal!  micro-acquisition.alpha.canada.ca/en/index.html".

Current draft french (262 chars): "Vous voulez être payé pour écrire du code #sourceouverte? Consultez les possibilités offertes sur le site Web de micro-acquisition. Le processus de candidature est simple, aucune cote de sécurité n'est nécessaire et vous êtes payé par carte de crédit ou Paypal! micro-acquisition.alpha.canada.ca/fr/index.html"

Simplier french wordings (231 chars): "Vous voulez être payé pour écrire du code #sourceouverte? Consultez le site Web de micro-acquisition. Le processus de candidature est simple, aucune cote de sécurité n'est nécessaire et vous êtes payé par carte de crédit ou Paypal! micro-acquisition.alpha.canada.ca/fr/index.html"

**Comment by gcharest** [comment]
Removed the "e" as it's the code that is open and capitalized first letter of individual word. Makes easier to read and it's my understanding that it now gets picked up by screen readers. Another option for French would be to use "Logiciel libre" in the hashtag.
> Vous voulez être payé pour écrire du code #SourceOuvert? Consultez le site Web de micro-acquisition. Le processus de candidature est simple, aucune cote de sécurité n'est nécessaire et vous êtes payé par carte de crédit ou Paypal! micro-acquisition.alpha.canada.ca/fr/index.html

**Comment by RachelMuston** [comment]
Tweeted and pinned on June 30
