### ISSUE TITLE
MA - lessons learned from opp 1

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1793]

**Comment by smellems** [comment]
- [ ] Debrief with team members
- [ ] Review google analytics
- [ ] Survey to suppliers

**Comment by RachelMuston** [comment]
Meeting held with team.
Documented here: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/User%20documentation/Admin/Lessons%20learned/Opportunity%201%20-%20lessons%20learned.docx?d=w795e05be268d40ccbb02a258025fb6be&csf=1&web=1&e=q0150v
