### ISSUE TITLE
Website Feedback 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#183]
- [x] Add Contact header 

1. Create Issue 
2. Email 
3. Submit Pull Request (for techies) 

- [x] Distribution mailbox

**Comment by gcharest** [comment]
What's the contract header?

**Comment by gabrielcossette** [comment]
@gcharest Typo. It's rather "Contact" header ;)

**Comment by gcharest** [comment]
Ah, makes more sense now lol

Le jeu. 15 août 2019 11 h 04, Gabriel Cossette <notifications@github.com> a
écrit :
