### ISSUE TITLE
MA - Auto-response messages from our generic mailbox to Notify is a problem

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1832]
Every time someone sends us something via a GC Form, it gets sent to our generic mailbox via notify.  Our generic mailbox then tries to send our auto- response to Notify.  This always fails as Notify is not set up to receive messages.

The result is a lot of unwanted failure to deliver messages in the inbox. 

"Your message was not delivered.
The email address cds.forms.formulaires.snc@notification.canada.ca is not able to receive messages since this feature has not been set by the sender."

**Comment by gabrielcossette** [comment]
Resolved by adding the mailbox in Outlook as an "independent" one and adjusting the reply rule. 👍
