### ISSUE TITLE
MA - Review of the translated screens for how to get a GitHub account

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1848]
File to review is here:
This file is required for any winning suppliers who are french speaking and who must work on GitHub but don't have an account yet.
https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/User%20documentation/Admin/rejoindre%20GitHub.docx?d=w90c507c08a854834b8f58877b34d41d5&csf=1&web=1&e=uAaMQR

**Comment by gabrielcossette** [comment]
Reviewed and good to go! 👍
