### ISSUE TITLE
Transition to Partner : 'Focus On Right Tool'

### ISSUE THREAD

**Issue by ShadeWyrm** [sara-sabr/ITStrategy#190]
I'd like to propose/request adding an 8th section - ideally in the position of #1 that states something along the lines of :

"Right Tool is the Driving Force Behind Development Practices'

Essentially, focusing on the following:
* Right Tool commits to the use of Open Source software where available over proprietary
* Right Tool takes into account current expertise, but more importantly future state expertise the Department wishes to grow.
* Right Tool commits to being Cloud native, and avoiding Architecture tied to on premise infrastructure.
* Right Tool focuses on User Centric Design
* Right Tool does not simply digitize a process.

**Comment by gcharest** [comment]
This need to be incorporeted to IT Picture Long/Medium term.

**Comment by gcharest** [comment]
Closing as will be addressed in #177
