### ISSUE TITLE
IT Strategy Timeline

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#191]
### Notes

   * Measure other countries' digital transformation to benchmark ourselves on (E.g. EU, India, Estonia, UK, US, Taiwan?)
   * Search main trends
       * Cloud (?)
       * OneGC
       * Digital Identity
       * Mobile Workforce
       * Work Profile in ESDC (e.g. developers, service canada agents, management)- % of workforce
       * AI in Service Delivery
   * Look at RFPs to dissern what the government's timeline may be
   * Number of meetings (lean governance statements in medium/long term to automate compliance) - work in the open  and automation should reduce needs for committees (e.g. ARC, CAB, if using CI/CD)
       * % of delegates
       * % of time can't attend
   * Performance metrics on service delivery (IITB services, not just ESDC) - service culture/bi-modal
       * processes are documented and shared transparently
       * SA\&A results available to other departments (e.g. SaaS assessments)

### Action Items

- [x] (@smellems, @gcharest) Contact TBS for OneGC timelines
- [x] (@smellems, @gcharest, @gabrielcossette) Contact TBS for Digital Identity
  - [x] @gabrielcossette to look for recent material
  - [Presentation to GC EARB in May](https://gcconnex.gc.ca/file/view/48741435/gc-earb-2019-05-02-09-sign-in-canada-way-forward-pdf)
  - [x] @smellems @gcharest to contact TBS as required
- [x] (@jaysonmc) Look for Estonia original timeline for X-Road
- [ ] (@remyb2canada) reach to SSC WTD - mobile and corporate network?
- [ ] (@remyb2canada, @jaysonmc, @arushisharma19) other countries as benchmark (service delivery)
- [ ] (@remyb2canada) contact HR on work profile and trends
  - [ ] Also look at (annual?) CS demography metrics on GCpedia (related to CIOC I Believe)
- [x] (@gcharest, @remyb2canada) Review Long Term Vision document

**Comment by gcharest** [comment]
So, what is missing? Do we need anything else here for calling it a day? @jaysonmc you mentioned some material that could be improved?

**Comment by gcharest** [comment]
Related to #175

**Comment by gcharest** [comment]
Need end dates: need volunteer on data quality/research

Need to move to JSON so that it works in ESDC network

**Comment by jaysonmc** [comment]
@gcharest Did we move to JSON? 

Also, do we still think this needs to be done to add language/items regarding digital ID and so forth? We can close if no longer relevant ...
