### ISSUE TITLE
Highlight Search on Website

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#193]
On the front page (where we have all the links) add a search box where, when you type, it will scan the pages and look for matching (or near matches and synonyms). If it finds some, highlight the link. 

Possible other features ...
- If 0 matches, highlight red 
- If %100 > x > %0, highlight orange 
- If 100% match, highlight green

**Comment by gcharest** [comment]
Highlights are great but if I remember correctly, colours should be avoided
to note differences as not everyone can perceive them. Let's start with the
search feature and we'll see what works best!

**Comment by gcharest** [comment]
#256
