### ISSUE TITLE
How to send feedback page

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#196]
Add a reference (separate page or inline paragraph) to both IT Picture pages (medium and long term) describing how one can send feedback to IT Strategy team.

**Comment by gcharest** [comment]
Related to #183 I think.

**Comment by gcharest** [comment]
I think we can add this as part of the disclaimer? This would be easily done and would be applied to all pages across the site?

**Comment by gcharest** [comment]
Need to be more generic title.

**Comment by gcharest** [comment]
Similar to #183

**Comment by remyb2canada** [comment]
add french version
