### ISSUE TITLE
Improve Useability of Site 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#213]
Comments from other groups indicate it's not clear who we are, or what we are aiming to do when they visit out site 

- Contact comms 
- Brainstorm how to improve site usability 
- Implement said changes

**Comment by gcharest** [comment]
Introduce sections per categories of pages. E.g.:
- About us
- Currently being developed
- Being reviewed
- Archived

Could also not list all documents on front page but rather make use of the menu:
- Our documents
- Our blog posts
- Our presentations (would probably need a small description for all presentations)
- Our maps

Etc.

This way, it would keep the front page cleaner.

**Comment by gcharest** [comment]
Categories should be displayed in each page.
Dates reviewed should also be displayed.
