### ISSUE TITLE
Perform Technical Options Analysis

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#216]
Search for potential solutions and present options

**Comment by smellems** [comment]
Initial findings

BPMN 2.0 is an open standard used to model business processes that is part of [Directive on Service and Digital - Appendix A: Mandatory Procedures for Enterprise Architecture Assessment](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=32602).

http://bpmn.io/ - OSS tools to edit BPMN, DNM and CMMN!

[Camunda](https://camunda.com/) - Workflow and Decision Automation Platform
BPMN: Yes
https://hub.docker.com/r/camunda/camunda-bpm-platform

[Joget](https://www.joget.org/) - Low Code Application Platform
BPMN: ??
Docker: https://hub.docker.com/r/jogetworkflow/joget-community

[Bonita BPM](https://www.bonitasoft.com/bonita-platform)
BPMN: Yes
Docker: https://hub.docker.com/_/bonita

Sharepoint Workflows
https://support.office.com/en-us/article/all-about-approval-workflows-078c5a89-821f-44a9-9530-40bb34f9f742
https://support.office.com/en-gb/article/all-about-collect-signatures-workflows-ee27dc94-8b8d-4d2b-898c-1754a397cb2b
https://support.office.com/en-us/article/all-about-collect-feedback-workflows-a0fd6fc5-0625-4aef-a41f-40aadbc9d946

**Comment by gcharest** [comment]
Draw.io supports BPMN as well

Le mer. 4 sept. 2019 15 h 09, Sébastien Lemay <notifications@github.com> a
écrit :
