### ISSUE TITLE
Develop wireframe of automated Software Onboarding

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#217]
- [x] Submit on [SABR Grassroots program](http://dialogue.hrdc-drhc.net/grp/IP/SitePages/InnovationHomeTest.aspx)
- [ ] Automate dependencies vulnerability scan
- [ ] Automate licence compliance
- [ ] Obtain Office 365 accounts and assess capabilities (@gabrielcossette)

When working on this need to use CATS 13671 code

Note: Accessibility out of scope for now

Link with issues #126 and #218 

Onboarding process [described here](http://dialogue/grp/PMS-SMP/SitePages/Business-Processes.aspx). Look at the 19 policies the process looks at complying.

[Grassroot idea submission here](http://dialogue.hrdc-drhc.net/grp/IP/Lists/Discussion%20Board/Flat.aspx?RootFolder=%2Fgrp%2FIP%2FLists%2FDiscussion%20Board%2F85%5f%2e000)

**Comment by jaysonmc** [comment]
Curent wireframes for software onboarding here: 

https://github.com/sara-sabr/ITStrategy/blob/master/drawio/en/SoftwareOnboarding.drawio

**Comment by jaysonmc** [comment]
Presentation at ARC: Late February 
Presentation at OCMC: TBD

**Comment by ElminaIusifova** [comment]
The prototype can be found here PR: SW-O prototype #610
