### ISSUE TITLE
GCWCC digitization

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#219]
e.g. put some credit card processing in the hands of canvassers

**Comment by gcharest** [comment]
Canvassing also includes registration to auto enrollment at pay. The form is paper but there's a platform available in use at CRA.

**Comment by gcharest** [comment]
https://www.canada.ca/en/campaign/charitable/give-now.html

NCR is eligible, regions are stuck with paper.

**Comment by gcharest** [comment]
Credit Card processing would work but need to act fast as software/service onboarding may take a while.

Also, need to look at paid options so include procurement early on.

Finally, this has to be looked with a national perspective, not just NCR. Remote offices may want to participate but be left out if the scoping doesn't include them.

**Comment by gcharest** [comment]
@jaysonmc closed?

**Comment by gcharest** [comment]
Email sent
