### ISSUE TITLE
show stoppers for IT Picture Long term

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#225]
5 year term: how implementation
10 year term: only outcomes (as implementations will change)

Citizens
- [x] @jaysonmc rephrase introduction about different audiences
- [x] @jaysonmc remove "may" from Citizens may receive their services
- [ ] @gcharest  rephrase Generational change: 
- [x] @jaysonmc  rephrase 2nd line under Auto enrolment (Canadians who do not opt out benefit seamlessly from GC services through the set of services they opt in to.)
- [ ] @gcharest rephrase 3rd bullet (One GC) - add Privacy lingo in the sentence 

Private Sector
- [x] @gcharest change private sector to External Partner (and define the breadth of what that means). Talk about startups, language about growing them, provide infrastructure, something about helping them (e.g. citizen's data, not ESDC's)
- [ ] @jaysonmc change "endpoint" lingo with something much more business lingo

IITB-ESDC
- [x] @jaysonmc, remove "where possible" for automating standards, by default. If there are exceptions they are handled
- [ ] reword CD to be more business lingo. 
- [ ] CD, how business lines/external partners write software and that IITB provides them with the support to host and deploy them to prod (IITB is a provider of tech services)
- [ ] continuous learning too fluffy,
- [x] change IITB-ESDC with ESDC and IT (and not even mention to IITB)
- [ ] remove lingo on devops and cloud, focus on outcomes

**Comment by gcharest** [comment]
closed in #227
