### ISSUE TITLE
Address DS's comments

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#231]
See email from 2019-09-02

**Comment by jaysonmc** [comment]
- More references needed 
  - At least one reference per line. No data or claim should be without evidence 
  - Ensure references to existing plans (Digital Operations Plan)
- Remove the wes and thems, etc.  
- Justify need for kiosks in paperless world 
- More clearly dddress delivery of services to non-digital citizens 
- Display in more interesting way

**Comment by gcharest** [comment]
I think kiosk should be looked at differently or justified for people at
risk or isolated.

Might be done through local access, personalized services and vast outreach
programs in collaboration with provinces, municipalities, schools and non
profits instead.

Need to look at ESDC vision for this one as well as what is done in other
countries for people that do not have access to internet, are isolated and
vulnerable. I can share a few examples, including an article regarding a
veteran.
