### ISSUE TITLE
CMC Executive Briefings on the manifestation of the Digital Policy

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#232]
DISMISSED
issue #445 takes precedence

Prepare a BN on the manifestation of the Digital Policy at ESDC. In collaboration with SSPB.

BN is not about describing the new Policy. It's about describing the changes needed to occur and how the new operating model would look like.

[BN in our sharepoint here](http://dialogue/grp/BU6810070/Versioned%20Library%20for%20collaboration/Briefing%20Note%20to%20the%20DM%20on%20the%20implementation%20of%20the%20TB%20Digital%20Policy.docx)

*LAST UPDATE*: on hold. Need further analysis, especially on the financial side

**Comment by gcharest** [comment]
Should relate to our work on defining IT picture as well as our upcoming strategies I guess :thinking:

**Comment by remyb2canada** [comment]
2019-10-25 update: awaiting feedback from MM and DS (by 2019-10-29)

**Comment by remyb2canada** [comment]
On hold. 
Needs more analysis before continuing (i.e. do the actual analysis on what needs to change in the CMC/MPIB committees and state those change int the BN).

Need to still engage with SSPB at working level.

I'm thinking the BN should be co-jointly written from both ADMs, not by DGs
