### ISSUE TITLE
Prepare for Denis Thursday meeting 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#233]
- Craziest things we've found, this evidence, and solutions

**Comment by gcharest** [comment]
Key elements we found:
- Software onboarding process could be improved
  - many issues have been created that seem related to this one: #117 #126 #192 #217 #218 Propose they all be combined in a single issue to make it easier to track unless there are specific actions needed
- GCWCC options to make more digital (#219):
  - Lots of options already in [place](https://www.canada.ca/en/campaign/charitable/give-now.html), key issue is with random canvassing of money during activities via credit card vs hard cash. The credit card option requires each person giving to visit the website itself vs having the canvasser do a transaction with someone else's credit card, a bit a la Square.
