### ISSUE TITLE
Meet with OAS/CPP SIS leads

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#236]
Related to #159

Need to setup meeting.

**Comment by jaysonmc** [comment]
I moved this to in progress? I have a meeting setup for BDM but not for OAS of CPP ... 

Anyone action these? I did mention getting in cahoots with business in an e-mail to the tech debt folk today, though I'm not sure that qualifies as in progress ..

**Comment by jaysonmc** [comment]
Email sent to admin to setup meeting upon his return to the office
