### ISSUE TITLE
Article about prioritization efforts leading to confusion

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2396]
DM CEPP, ESDC Priorities, ESDC IM/IT Priorities, SSC, Departmental DSP and Sustainability Apps by projects.

Using projects as language for everything instead of service or product roadmaps.

ideas:
- DM-level comms (fluff)
- executive-level comms (fluff)
- working level comms (klingon)

**Comment by pabrams** [comment]
Are projects still the prevailing unit of funded work because TBS still funds by project, and not product?
