### ISSUE TITLE
IT Picture - address AG comments

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#241]
- [x] remove OAS from our vision (ESDC's service vision is a lot more than OAS)
- [ ] by "business" he meant the business of IT. Not necessarily the business of ESDC
- [ ] Lean IT Governance is good. But perhaps should be rephrased as "Lean Organization"
- [ ] Ignore the financial aspect. Just focus on where we want to be. The financial will come afterwards as a strategy portion on how to get there
- [ ] What we do today will be done tomorrow; and more. So our current IITB Org Structure explains what is done for IT. This needs to be reflected in the picture, though may not be the same org structure
- [ ] ESDC employees consume IT to do there job. This needs to be reflected in the IT Picture
- [ ] Monday 2019-09-16 feedback in [OneNote](http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Notes.one#2019-09-16%20Armand&section-id={8F7042FC-8CA2-4132-A942-B030364A6FE4}&page-id={C2E82655-7820-45E4-98BB-21AA7C1E1396}&end)

**Comment by gcharest** [comment]
Also consider #231 (closed for now)

**Comment by gcharest** [comment]
Clarified that "by "business" he meant the business of IT. Not necessarily the business of ESDC" actually meant that this piece was missing. There's a principle and a "tangible" picture to draw.

**Comment by remyb2canada** [comment]
Approach is to focus on core competencies as opposed to functions of the organization.
