### ISSUE TITLE
Member Onboarding

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2419]
update the [OneNote section accordingly](https://014gc.sharepoint.com/sites/IITB-ITStrategy/_layouts/15/Doc.aspx?sourcedoc={d78fa29b-cc7c-43b4-a2fb-b380d2e61474}&action=edit&wd=target%28Onboarding.one%7C89356fa5-ff3d-4426-a718-66fa2f44e72b%2FNew%20Employees%7Ca4d3a671-9bc5-415a-b6ce-fc099c5a5de6%2F%29&wdorigin=NavigationUrl).

**Comment by RachelMuston** [comment]
One note updated :)
