### ISSUE TITLE
Add header for navigation

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#243]
For quick navigation add 

- About us 
- Documentation
- Issues
- Blog Posts 
- Workspace 

into header and/or footer

**Comment by gcharest** [comment]
This differs than #242 as I would use these sections in the top right end menu instead:

Reach different sections

The notice's purpose in #242 is a notice. In fact, we already have a "View on Github" link at the bottom that links to the document displayed.

E.g.: if you're on mandate, the "View on Github" link sends directly to mandate.md. If you're on reference materials, it sends you directly to the references.md

@smellems What do you think?
