### ISSUE TITLE
SABR AllStaff - Investigate the use of Deep Fake for a video of DS

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#247]
- [ ] Investigate the use of Deep Fake for a video of DS, including the generation of texts by machine (NLG) -> investigate with R&D
- [ ] look at Slack's post on opensource deepfake libraries

**Comment by jaysonmc** [comment]
Can't seem to find a good app for this ... found face swap from Microsoft but pretty meh. Also doesn't do moving pictures. Zao is supposed to be good but privacy issues though more importantly ... I just cant seem to find it on the app store.
