### ISSUE TITLE
IT Picture - Medium - Comments from CB

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#250]
- [ ] Consider increasing scope to digital strategy.  As we’ve mentioned, modern IT isn’t as much as barrier as are the current Acts, Policies, Standards, processes.  A digital strategy has a broader sense and it’s time we stop simply looking for the low hanging fruit …. Time to climb the tree 
- [ ] Your themes are very “digitally” focused (how should business evolve and thrive in a digital age vs. what technology should we use to enable the digital strategy)
- [ ] Need to “set the stage” before asking our Partners to comment.  This is a very process driven, governance based organization, if you don’t immediately ask them to look at this from a different lens, they will use the approach they are accustomed to.
- [ ] Should consider Federal + P/T&MASH, Provincial/Territories, Municipalities, Academics, Schools and Hospitals
- [ ] Centralized login should be at minimum thought about at the Federal Level or at minimum for Key/Visible citizen service.  Part of the OneGC vision 
- [ ] Service Centres and Outreach should also consider “anywhere” think of our citizens up north (very north) 
- [ ] I’m assuming this vision is in response to the Government’s Digital Policy could be good to make the link (this has a foundation)
- [ ] Consider thinking about an open Funding Model where it doesn’t take years to ask, receive approval, fence in the fiscal framework and convince TBS that you know what you doing so you can access the funds against things you said you would do years ago, that now have evolved and changed
- [ ] Culture:  If need to map everything out in advance (Scope, Costs, timelines), go through a rigorous governance  and course correction is considered a negative thing, then how can we ensure that we are continuously learning, adapting and implementing the best strategies?  Create a culture of acceptable risk.
- [ ] IITB-ESDC – still appears reactive me to, where is our research centre exploring, testing, recommending? We need to get ahead of the curve
- [ ] Internal IT Services – These aren’t all “services” at least not from a Client’s perspective.  IITB needs to be come focused on delivering value to the department and less on processes that it make its job easier.
- [ ] Culture: stop assuming that clients aren’t technical or that their recommendations for solution have not been well thought out.

**Comment by gcharest** [comment]
#241 #250 need to be looked at as part of this issue.
