### ISSUE TITLE
Publish IITB Diagnostic Study materials blog post

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2574]
- [x] Purpose and objectives
- [x] Interview Questions
- [x] Field Guides
- [x] Rough idea of communication materials and planning artefacts

**Comment by RachelMuston** [comment]
Draft of the blog post is here for review: https://014gc.sharepoint.com/:w:/r/sites/IITB-ITStrategy/Shared%20Documents/Blogs/Drafts/Doing%20a%20Diagnostic%20Study.docx?d=wf35490df72294cdea1b14237aae7f87e&csf=1&web=1&e=5B6Kp1
