### ISSUE TITLE
Review Strategy Document

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2619]

**Comment by RachelMuston** [comment]
Latest comments from the Testing Services Team have been incorporated. @remyb2canada over to you for review. :) https://014gc.sharepoint.com/:w:/r/sites/IITB-ITStrategy/Shared%20Documents/STRATEGIES%20AND%20INITIATIVES/SMO%20-%20Strategy%20Management%20Office/Client%201%20-%20Testing%20Services/Strategy%20Plan-Testing%20Services.docx?d=wde1e3a58ec684d5ba4a5cdf1f8f3d74e&csf=1&web=1&e=d7c9S4
