### ISSUE TITLE
Confirm what documents will be shared for audit - AG

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#264]

**Comment by gcharest** [comment]
Way forward
- Presentation
- Document

IT Picture
- [Medium term](https://sara-sabr.github.io/ITStrategy/it-picture-medium-term.html)
- [Long term](https://sara-sabr.github.io/ITStrategy/it-picture-long-term.html)

**Comment by jaysonmc** [comment]
+ Strategic Roadmap 

That seems to get a lot of love from mgmt
