### ISSUE TITLE
Process to bring in Free Agent

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#265]

**Comment by jaysonmc** [comment]
Waiting on response from free agent 
- Budgeted for 
- Have mgmt approval
- Have verbal agreement with free agent

**Comment by jaysonmc** [comment]
- Document completed 
- Inqury sent to HR (pending)

**Comment by jaysonmc** [comment]
Modified document sent for review

**Comment by jaysonmc** [comment]
Confirmation received from resource

**Comment by jaysonmc** [comment]
Sent for approval

**Comment by jaysonmc** [comment]
Letter signed by all parties.

**Comment by jaysonmc** [comment]
Confirmation of space received
