### ISSUE TITLE
Update copyright notice

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2663]
from

> Copyright © Her Majesty the Queen in Right of Canada, as represented by the Minister of Employment and Social Development Canada, 2019-2020.

to

> Copyright © His Majesty the King in Right of Canada, as represented by the Minister of Employment and Social Development Canada, 2019-2020.

**Comment by RachelMuston** [comment]
New plan :-)
remove the copyright text from the footer and update the license file to replace the existing copyright text with: Copyright (c) 2019 Government of Canada - Gouvernement du Canada
