### ISSUE TITLE
Document existing software assessment process in ESDC

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#285]
Initial Epic: #218

**Comment by gabrielcossette** [comment]
Documentation saved in SharePoint: http://dialogue/grp/BU6810070/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fgrp%2FBU6810070%2FShared%20Documents%2FProjects%2FSoftware%20Onboarding%2FAccessibility%20Criteria&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

**Comment by gcharest** [comment]
Could we please have an update on this issue @gabrielcossette? Thanks!

**Comment by gabrielcossette** [comment]
Met with the team in October but didn't receive the documentation. Sent a reminder.

**Comment by RachelMuston** [comment]
Added a file to the Sharing Software Assessments folder documenting what we know of the software assessment process at ESDC so far.
