### ISSUE TITLE
Update GCcode presentation for IITB DG Committee

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#289]
https://github.com/sara-sabr/ITStrategy/blob/master/presentations/en/GCcode-Version-Control-for-ESDC-and-GC.md

- [x] Directive on Service and Digital, Mandatory EA assessment, Digital Standards
- [x] Clarify ask: Sharing/reuse in GC, make GCcode officially supported
- [x] For all source code, not just OSS
- [x] This is not just a copy of the code, it's where teams work
- [x] Difference between public, GC wide, ESDC only
- [x] SaaS (Github.com, Gitlab.com, Bitbucket.org) vs GCcode (self hosted Gitlab)
- [x] More than Git (Groups, Repos, Issues, Kanban, Wiki, CI)
- [x] Moving from GCcode to SaaS
- [x] Pages
- [x] CI and Runners
- [x] How do we decide where to host our code/projects?
- [x] Accessibility
- [x] Security

**Comment by remyb2canada** [comment]
@gabrielcossette @smellems I recommend adding as benefits to IITB:
- remediate and manage technical debt

And reference the [DORA 2019 State of DevOps report](http://dialogue/grp/BU6810070/Shared%20Documents/Reference%20Materials/DORA-state-of-devops-2019.pdf), page 57, that shows code maintainability and measurement (two features GCCode can provide) are key constructs that negatively impacts technical debt.

Another next step can be to evaluate the use of GCCode as part of the OASIS project and Technical Debt remediation activities.

**Comment by gabrielcossette** [comment]
Great suggestion @remyb2canada! Added it, will be in the next GCcode PR.
