### ISSUE TITLE
IT Strategy Website - Privacy Impact Assessment

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#296]

**Comment by gcharest** [comment]
Useful links: https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/interpretations_02/

IP can potentially be defined as private information under certain contexts.

**Comment by gcharest** [comment]
[Expectations: A Guide for Submitting Privacy Impact Assessments to the Office of the Privacy Commissioner of Canada](https://www.priv.gc.ca/en/privacy-topics/privacy-impact-assessments/gd_exp_201103/)

[Directive on Privacy Impact Assessment](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=18308)

**Comment by jaysonmc** [comment]
Also useful reference 

Why think about privacy? by  Office of the Privacy Commissioner of Canada

https://www.youtube.com/watch?time_continue=16&v=PhU7RsUia14

**Comment by jaysonmc** [comment]
http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Tasks.one

Navigate to PIA file on the right hand side

**Comment by gabrielcossette** [comment]
Contacted Privacy Team regarding draft Privacy Notice for website. Analyst has been assigned to the file.
