### ISSUE TITLE
Update profile page with personas for IITB

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#297]
Update this page
https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/employee-profiles.md

**Comment by myp192** [comment]
Currently doing some information management with the meeting notes to "build the puzzle" for the personas.

**Comment by smellems** [comment]
Notes from yesterday's meeting.

For each persona, look at
- what does this user use technology for
- what outcomes are they producing
- how many levels away from the client are they

Outcomes should be specific, or be split into more personas.

Map business capabilities to outcomes.

Next: layered - systems of records, systems of differentiation, systems of innovation, ..
