### ISSUE TITLE
Add more "tangible" examples to GC-Wide and IT in ESDC

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#302]
In the medium term, we currently mention the shift to using the cloud, open standards, open source and agile project management.

Need to add
- mobile workforce with mobile devices and GCworkplaces
- define increased use of cloud..
- ..

**Comment by gabrielcossette** [comment]
Timely, there was a GCMobility presentation this afternoon: https://gcconnex.gc.ca/file/view/53976272/gc-mobility-presentation-october-9th-2019
Project Repo: https://gccode.ssc-spc.gc.ca/canadas-free-agents/gcmobility
GCcollab: https://gccollab.ca/groups/profile/2183003/engcmobilityfrgcmobilitu00e9

**Comment by gcharest** [comment]
Also thinking on expanding about reusability of solutions. Push for infrastructure agnostic architecture and tools.
