### ISSUE TITLE
Create draft SLF Presentation - IT Strategy team

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#321]
Prepare a presentation for the Senior Leadership Forum with the following goals:

- Communicate the existence of a new IT Strategy team and its mandate to IITB
- Raise Awareness on the IT Strategy's team current area of focus: core competencies
- Set the stage for upcoming engagements with IITB teams

SLF presentation scheduled for Jan 29th, 2020

need to send presentation to Governance, in  French and English, **by COB on January 23**

**Comment by jaysonmc** [comment]
Scheduled for January 29th
