### ISSUE TITLE
Blog - Stopping the promotion of risky behaviours

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#329]
A case to change how we do IT as a means to reduce its risks.

Explains the conventional method of doing IT is framed in a such a way that promotes risky behaviours (funding large projects, making changes expensive). Cloud can enable us to do IT differently and reduce risks traditionally associated with it.

War & Peace & IT
https://github.com/18F/technology-budgeting/blob/master/handbook.md

May link to #327

**Comment by gcharest** [comment]
That would be a blog post?

**Comment by remyb2canada** [comment]
this task was done
blog here: https://sara-sabr.github.io/ITStrategy/2019/12/20/why-we-are-promoting-risks.html
