### ISSUE TITLE
Update IT Strategy mandate for CIOEC

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#335]
Update presentation of IT Strategy's mandate for CIOEC **[date moved]** to reflect updated mission statement.

Presentation URL: https://sara-sabr.github.io/ITStrategy/presentation.html?markdown=/en/2019-11-05-CIOEC-Mandate.md

**Nov 6th** prep meeting with AG

Package to send to CIOEC **by date moved**.

CIOEC presentation format rules:
Please ensure that your deck as the following: 

- [ ] All decks to include a purpose slide
If not using a deck format, please ensure purpose is included in documentation provided
- [ ] All materials are to be submitted in PDF format via a link
Links to documentation in a format other than PDF will not be accepted
Looking to use **[astefanutti/decktape](https://github.com/astefanutti/decktape)** to do so

- **Purpose of item (for discussion, for information):**  For discussion 
- **Duration of presentation:** 15 minutes
- **Description of item:** As per Denis’ commitment for full transparency in the creation of net new teams that support the Way Forward, the next team to present its mandate is the IT Strategy team.  This will allow DGs and the CIO to weigh in on the direction proposed to ensure the objectives support the priorities of the branch.
- **Rationale for item coming to CIOEC:** To present the team’s mandate where the CIO can share his expectations of outcomes with all DGs directly.

**Comment by gcharest** [comment]
I think this is completed @remyb2canada ?

**Comment by remyb2canada** [comment]
CIOEC Mandate Presentation and endorsement done on 2019-11-05
