### ISSUE TITLE
Investigate Solution for Kanban board summaries 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#337]
Directors moving to GitHub are asking for ways to view all potential projects (boards) they are responsible for at once 

[ZenHub](https://github.com/marketplace/zenhub/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW41OQ==#pricing-and-setup) may solve this need 
Other options

**Comment by gcharest** [comment]
Yeah, heard of the ZenHub service before. We can definitely discuss it's use :)

**Comment by gabrielcossette** [comment]
ZenHub looks interesting but it requires a browser extension?

**Comment by smellems** [comment]
I've used https://zube.io/ before and you can have multiple repos on the same board but like Zenhub I think it only works for Github.

Does it make sense to want to see all boards at once?  Tasks are supposed to be small, move across the board quickly and not represent whole projects or milestones.  Looking at a bunch of unrelated specific tasks will not be that helpfull.

What they need is a higher level board or learn to navigate milestones to see progression towards larger goals.
