### ISSUE TITLE
Digital Signature / Automated Docket Workflow

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#338]
Automate docket submission/senior mgmt approval process

Requested by mgmt 

Related to completed task #214
Once completed #318 could be integrated into this item

Work on this task needs to be tracked using CATS 13671 code

**Comment by smellems** [comment]
There is a milestone for this project.  All Issues should be linked there.

What is this issues for?  A prototype?

**Comment by smellems** [comment]
Workflow draft here https://github.com/sara-sabr/ITStrategy/blob/master/drawio/en/docket-approval.bpmn

Can be opened with https://demo.bpmn.io/
