### ISSUE TITLE
Set of IT Strategies

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#35]
- Do not compete with private sector
- All new project must have API
- No front-end development can be allowed
- All new project must be open sourced

**Comment by gcharest** [comment]
Partly fixed in #30

@remyb2canada We don't have KPIs for working in the open: 
- contributing to OSS
- releasing as OSS.

**Comment by jaysonmc** [comment]
Could add this into the presentation document, then close, oui? 

https://github.com/sara-sabr/ITStrategy/blob/master/TeamMandate/Presentation.md

**Comment by remyb2canada** [comment]
those are not strategies, they are guiding principles

**Comment by jaysonmc** [comment]
Proposing we close this as the discussion seems to have turned into a duplicate of [this](https://github.com/sara-sabr/ITStrategy/issues/48) #48
