### ISSUE TITLE
Strategy - Build vs Buy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#350]
From Director 

- Engage with Cloud and TA
- Comment on BN

**Comment by gcharest** [comment]
Issue is: What's the strategy on using SaaS vs Cloud hosted DevOps solution, BN being one example of such a situation.

**Comment by jaysonmc** [comment]
Presently working from here: https://github.com/sara-sabr/ITStrategy/tree/saasvscloudStrategy

**Comment by remyb2canada** [comment]
Should we position Cloud as being the ability to manage infrastructure as a software (infrastructure as code)?
And SaaS as moving the responsibility towards the vendor which means also escalating vendor locking risks?

The game changer that Cloud brings for DevOps is that agility of infrastructure as code.
SaaS first, though in the policy, does not mean SaaS always. And it would be dangerous for organizations to bring their "special sauce" within a SaaS. SaaS may therefore be a much better option for productivity tools that have been commoditized (e.g. collaboration, financial and HR systems), less about "special sauce" stuff (e.g. business rules)

**Comment by jaysonmc** [comment]
Meeting took place yesterday

- Flow chart collaboratively created
- New skeleton for new document created

Will be creating new branch with new document and created flowchart

**Comment by jaysonmc** [comment]
https://github.com/sara-sabr/ITStrategy/tree/buildvsbuystrategy

**Comment by jaysonmc** [comment]
https://github.com/sara-sabr/ITStrategy/blob/buildvsbuystrategy/_pages/en/buy-vs-build-strat.md

Work on pause pending blitz meeting tomorrow afternoon

**Comment by jaysonmc** [comment]
Didn't mean to clkose ... clicked the wrong button

**Comment by jaysonmc** [comment]
#452
