### ISSUE TITLE
Agile Coaching

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#355]
Spend time with teams helping on board to work in alignment with strategies, such as working in the open, breaking silos, collecting metrics, tracking work, and using modern tools and technologies.

**Comment by remyb2canada** [comment]
I recommend reaching out to the Interop team. They have a consultant that is a guru on the subject and has good success in coaching people to move towards working in an agile method

**Comment by jaysonmc** [comment]
https://github.com/sara-sabr/sdlc created 
https://github.com/sara-sabr/BRM-GRA created
