### ISSUE TITLE
GC Sharing of Software Approvals 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#362]
(a11y, security, etc...)

Similar but different than issue #384

**Comment by remyb2canada** [comment]
Is there a way to increase the visibility of issues so that this one gets for sure in our to-do list next sprint?

😄

**Comment by remyb2canada** [comment]
duplicate of issue #384

**Comment by gcharest** [comment]
Add broad Terms and Conditions (OSS, versions of SaaS T&Cs, etc.)

**Comment by gabrielcossette** [comment]
Milestone created. Will spin new issues for the work.
