### ISSUE TITLE
Build Presentation for MTLC (Managers’ and Team Leaders’ Community)

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#368]
For future event (probably December or January)

Proposed format (by Guillaume):
- Who we are what we do
  - Questions
- Managing virtual team
  - Working in the open
  - Trust
  - Questions
- Tools and techniques
  - Questions
- Call to action

**Comment by myp192** [comment]
Is this regarding the shared panel for November ? The presentation can only be done in December for the hour and a half.

**Comment by gabrielcossette** [comment]
Yes, this is about the Nov. 13th event.
I don't understand. The presentation can only be done in December?
