### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#40]
Need to review folder structure and delete all historical documents no longer.

**Comment by gcharest** [comment]
Started cleaning up the documents in #42 

Need better set of folder structure but also content.

- [ ] Images will reside in a single place (use link to incorporate)
- [ ] Remove versions no longer required since it stays in the history anyway (e.g.: team mandate individual versions)
- [ ] Present relevant content in a logical and accessible way (using Pages)

**Comment by gcharest** [comment]
Old mandate files have been removed (accessible via folder history) in #42

**Comment by jaysonmc** [comment]
I also propose creating a "How To" for things like the beginner Git tutorial by @arushisharma19

**Comment by gcharest** [comment]
Totally, I think I had started with the npm run test explanations.

Will look into it 😉

**Comment by jaysonmc** [comment]
@gcharest Can we consider this done now?

**Comment by gcharest** [comment]
More work required on pages so that content become highly consumable.

Will loop in @smellems

**Comment by gcharest** [comment]
Too many working documents right left and center. I had someone external provide a quick feedback: No clue where things start, there are duplication of strategies, etc.

Need to clean up the repo even though we're in that nice little phase where everything is a mess :smile:

**Comment by smellems** [comment]
The bilingual Jekyll add the `_pages` folder that will contain English and French versions of "final" documents to be published on the Website.

In #79 I add a `presentations` folder that will contain English and French versions of presentations.  All presentations here would be viewable from the Website as "slides".

I propose that we move other folders ["Ideation", "ReferenceMaterials", "Roadmaps", "Strategies", "TeamMandate"] to a `Working-Travail` or `Draft-Brouillon folder.  Files would be moved from here to the `_pages` folder once ready for the Website.

**Comment by smellems** [comment]
We will move draft content to the `_draft` folder.  I suggest we remove current folders and keep only the files in `_draft/en`
