### ISSUE TITLE
Submit continuous improvement strategy for endorsement

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#415]
- 10% time for learning
- 10% time for automating and improving processes

**Comment by remyb2canada** [comment]
@smellems @jaysonmc , let's tie this with the new Policy on Service and Digital!

    4.5.1 **The departmental CIO** is responsible for:
        4.5.1.1Providing functional leadership in the department on the development and sustainability of the IT and information communities **through talent management and community development strategies**.
