### ISSUE TITLE
Comms Strategy To Promote Opening Up of Existing Docs

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#426]
Through communications, contact the org requesting those who are not dealing with protected information, remove the restrictions to their documentations/work to those on the internal network

Ex: 
- Remove permission restrictions on SharePoint sites 

**Contact IITB IM first** to leverage their efforts. Their [site is here](http://iservice.prv/eng/imit/ims/clients/index.shtml).

Use [IM's Strategy](http://dialogue/grp/GCDocs/Strategic%20Direction/IM%20Strategy%20and%20Plan/For%20Deputy%20Minister%20Approval%20-%20Final%20IM%20Strategy%20and%20Roadmap/ESDC%20Information%20Strategy%202018-2023%20FINAL%20ENG.pdf) and [Guiding Principles](http://iservice.prv/eng/imit/ims/clients/im_guiding_principles.shtml).

**Comment by remyb2canada** [comment]
@jaysonmc That's part of the IM strategy already

They are even measuring that
