### ISSUE TITLE
Transition to Service Discussion

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#43]
So, few things:
- 1 & 3 Are somewhat related; plus 1 is supposedly taken already by CDO. Could still keep and support though.
- 3 is very technical and I'm not sure they will "see" the picture
- 6 shouldn't be tied to dollar figure like the current projects onboarding. Should also encourage micro-services architectures, self-contained applications as much as possible.

_Originally posted by @gcharest in https://github.com/sara-sabr/ITStrategy/pull/36#issuecomment-508658987_

**Comment by gcharest** [comment]
@jaysonmc @remyb2canada @arushisharma19 

I've merged the document after making the modifications we've discussed (I think it really sets a pretty solid picture).

I just had the comments above for us to discuss.

**Comment by remyb2canada** [comment]
Agreed. Was making changes while the PR was up but those changes are on my personal laptop :S

**Comment by remyb2canada** [comment]
>     * 1 & 3 Are somewhat related; plus 1 is supposedly taken already by CDO. Could still keep and support though.
>     * 3 is very technical and I'm not sure they will "see" the picture

Not yet confirmed whether it's CDO that does the Information Model or the Information  Architects within IITB.

For 3 being too technical, I'll re-word but we need to keep "API" in there. This should become a business term.

**Comment by gcharest** [comment]
Reviewed #43 with a few comments. Really like the changes @remyb2canada ! :smile:

**Comment by gcharest** [comment]
I think this is closed once we merge #49, @remyb2canada ?

**Comment by remyb2canada** [comment]
@gcharest yes. Making changes now and pushing soon

**Comment by gcharest** [comment]
So this is closed in #49
