### ISSUE TITLE
Do team headshots for About Us Page

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#435]
Create IT Strategy team identity page  with headshots of each team member and  description on who is doing what

Example from CDS:
https://digital.canada.ca/meet-the-team/

**Comment by gcharest** [comment]
The auto close feature is nice but this requires an input from everone to actually be closed:
@ElminaIusifova @RachelMuston @jaysonmc @remyb2canada @myp192 @smellems @gabrielcossette

**Comment by RachelMuston** [comment]
Should I be creating a file for my data under https://github.com/sara-sabr/ITStrategy/tree/master/_data/profiles?
I have a headshot pic, where do I put it?

**Comment by RachelMuston** [comment]
I've uploaded my headshot pic. :-)

**Comment by RachelMuston** [comment]
Team page is live! :). Thanks to @Moro-Code!
