### ISSUE TITLE
KPIs Additional Actions

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#44]
From discussion points in PR #30 , we need to:

- [x] Remove (or merge) 4 as it's a duplicate of 3 based on discussion.
- [x] Identify different metric for 6: project intake/completion vs product management (I'm sure Gartner has something wink )
- [ ] Add a KPI for Resilience to complete the reduction in issues (7)

**Comment by remyb2canada** [comment]
Need to further evaluate how KPI for resilience can be measured

**Comment by gcharest** [comment]
Issue related to #43

**Comment by gcharest** [comment]
NVM, that's #47 

Yeah, the Cyber ones we may want to touch point with ITSec and TBS Cyber. There's guidance already in place AFAIK.

**Comment by gcharest** [comment]
Will create an issue for this specifically and close this one.
