### ISSUE TITLE
IM Policy Review

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#446]
Requested by director

BF by Monday 25th

Put all comments in here: https://mensuel.framapad.org/p/esdc_im_policy?lang=en

format: 
[comment number] - doc page/segment 
... the comment ...

those comments will be sent to Director on Monday 25th

**Comment by gcharest** [comment]
I've added my comments - Removing myself from this task :wink:

**Comment by remyb2canada** [comment]
@jaysonmc I believe we can send the comments to Director then close the issue

Comments [in framapad](https://mensuel.framapad.org/p/esdc_im_policy?lang=en), or in this [standard word document](http://dialogue/grp/BU6810070/Versioned%20Library%20for%20collaboration/Reviews/ESDC%20Information%20Management%20Policy_ITStrategy_Feedback.docx)

**Comment by remyb2canada** [comment]
Feedback sent to Director 2019-11-15
