### ISSUE TITLE
Update Communications Strategy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#473]
First draft was merged here
https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/strategy-communications.md

Review and add more information based on
https://knowhow.ncvo.org.uk/campaigns/communications/communications-strategy
or other examples.

- [ ] Add more ways to get things endorsed
- [ ] Add more ways to outreach

**Comment by myp192** [comment]
Currently transitioning the communication into a Stakeholder Engagement (Business language) if our goal is to seek the need to understand the reasonable expectation and interests of the stakeholders. This is help evaluate the strategic capabilities.
