### ISSUE TITLE
Draft text about IT strategies to go into PMAs

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#495]
Specific text for directors, managers and team leads

**Comment by jaysonmc** [comment]
http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Tasks.one

onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Tasks.one#Performance%20Management%20-%20Work%20Objective%20Proposals%20&section-id={0C201990-D9C1-4CF2-B096-E9470A666F8B}&page-id={8D64ECD9-18FD-466C-99FF-CB9CD28E9689}&end
