### ISSUE TITLE
Revsit Service Canada

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#509]
Issues list [in our sharepoint](http://dialogue/grp/BU6810070/Shared%20Documents/Projects/Service%20Canada%20Issues/Service%20Canada%20-%20Enjeux%20TI%20-%202019.docx)

Summary of findings by @remyb2canada [available here](http://dialogue/grp/BU6810070/Shared%20Documents/Projects/Service%20Canada%20Issues/Service%20Canada%20-%20Enjeux%20TI%20-%202019_summary_of_findings.docx). Includes 9 items though not all of them can be addressed by ESDC (some relate to IRCC's systems and corporate network)

**Comment by gcharest** [comment]
This is related to the list of issues that was shared to us.

**Comment by jaysonmc** [comment]
I cannot find the e-mail. I recall sending it to the team ... anyone :) ?

**Comment by gabrielcossette** [comment]
> 
> 
> I cannot find the e-mail. I recall sending it to the team ... anyone :) ?

Forwarded :)

**Comment by remyb2canada** [comment]
I have documented my list of findings in [this document](http://dialogue/grp/BU6810070/Shared%20Documents/Projects/Service%20Canada%20Issues/Service%20Canada%20-%20Enjeux%20TI%20-%202019_summary_of_findings.docx). Not exhaustive.

I'm seeing potential here:

- **#3 On Site Support:** work with ESDC's operations to propose an alternate support model, for one location to test first, and see if it's viable
- **#6 Network speed and general performance: ** Work with Enterprise Operations and Technical Debt team to propose an alternate working model, one that could make use of 3 different network: ESDC, IRCC, and Internet. Test this new model on one location to see if it's viable
- **#7 New employee onboarding: ** Grassroots initiative to create an automatic onboarding application that would automatically grant access to new service canada employees based on defined profile.
