### ISSUE TITLE
Need to define IITB toil

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#51]
How to measure reduction rate of IITB toil?

Rate = number of production release / number of personnel?

Rate = number of service desk requests (ITSM) / number of operations personnel?

**Comment by gcharest** [comment]
Number of automated process * human interventions / Number of manual
process * human interventions?

**Comment by jaysonmc** [comment]
Perhaps we need Lead Time analysis (or value stream analysis, whatever phrasing) first. 

Then we could map increases in efficiency to any hiring that took place.

**Comment by gcharest** [comment]
I think this is critical.

**Comment by gcharest** [comment]
That should probably be part of our strategies. To be reviewed.
