### ISSUE TITLE
Strategy : What we will not be doing

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#52]
Need to identify what we will collectively **not** be doing:

- Outsource our core/critical business applications
- Build/Purchase monolithic "solutions" --> Move towards a microservices architecture, whether it's leveraging OSS, purchased applications/services, or built apps/services.
- Etc.

**Comment by jaysonmc** [comment]
@gcharest 

That was what [this](https://github.com/sara-sabr/ITStrategy/blob/master/TeamMandate/Presentation.md) was supposed to be. 

So we could modify it as needed to make it more closely fit what you are looking for

**Comment by gcharest** [comment]
OK, whichever format we want, it all needs to weave together tightly.
