### ISSUE TITLE
Briefing Note to CIO on Policy on Service and Digital

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#542]
from issue #501 , BN to CIO

[BN available here](http://dialogue/grp/BU6810070/Versioned%20Library%20for%20collaboration/Briefings/2020-02-05-note%20à%20l'intention%20du%20sous-ministre%20adjoint%20-%20rapport%20sur%20l'analyse%20d'impact%20de%20la%20Politique%20Numérique.docx)

**Comment by remyb2canada** [comment]
Docket sent in blackhole March 6th...

**Comment by remyb2canada** [comment]
On hold due to COVID-19

**Comment by jaysonmc** [comment]
@jaysonmc to follow up

**Comment by jaysonmc** [comment]
Followed up with director yesterday

**Comment by jaysonmc** [comment]
@jaysonmc will follow up again

**Comment by jaysonmc** [comment]
Sent BN (and respective content) as part of our comments on the DOSP 2.0 (and its relevance to the Policy on Service and Digital).

**Comment by jaysonmc** [comment]
Report requested by Director and sent again

Closing for now, as it has been re-sent twice in the past few weeks. Will create  task to follow up

**Comment by smellems** [comment]
Should update based on new DOSP, and current situation..

**Comment by smellems** [comment]
BF to CIO for approval.

**Comment by smellems** [comment]
Now with DGO

**Comment by smellems** [comment]
All the way to the top!

Will be presented at SLF
