### ISSUE TITLE
Review existing CATS codes for duplicates

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#574]
We added a new CATS code for Continuous Improvement.
But there are many other codes for, learning, innovation, .. that could all be replaced by the new codes instead.

Identify these codes and ask about removing other codes replacing them with the new code.

**Comment by RachelMuston** [comment]
Email sent to CATS team on Feb. 13 asking about effort to reduce the number of CATS codes (also about risk of continuous improvement being attached to Jayson's CC and how we might do some reporting)
