### ISSUE TITLE
Questions for the IITB Stakeholder Engagement

### ISSUE THREAD

**Issue by ElminaIusifova** [sara-sabr/ITStrategy#603]
Draft questions for the user to get feedback on Continues Learning Strategy , collect the information and figure out persona 

links to issue #477

**Comment by ElminaIusifova** [comment]
Link to external link on Framapad is here: 
https://mensuel.framapad.org/p/9eki-t2vm0kg1cz?lang=en

**Comment by remyb2canada** [comment]
New framapad (cleaner version): https://semestriel.framapad.org/p/9eye-interviews?lang=en

**Comment by RachelMuston** [comment]
New New Framapad: https://mensuel.framapad.org/p/9f58-interview-questions?lang=en

**Comment by remyb2canada** [comment]
Pending review with test directors
