### ISSUE TITLE
Present books "The Architecture of Open Source Applications" to ARC

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#609]
Present books [The Architecture of Open Source Applications](https://aosabook.org/en/index.html) to ARC, as a learning resource + supporting our OSS objectives.

**Comment by remyb2canada** [comment]
Voir courriel envoyé à @gabrielcossette le 18 mars, 2020 à 13h55.
Au sujet du EA roadmap.

**Comment by jaysonmc** [comment]
Also add Linux Foundation OSS learning resources?
