### ISSUE TITLE
Make the case for 20% improvement

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#626]
Define outcomes

- Quality of service
- Reduce lead time for changes and delivery of services/devices
- Recover faster incidents and errors
- Reduce frequency of incidents and errors
- Increase ability to comply with regulations (GC digital, ..)
- Student retention
- Job satisfaction
- Acquire new essential skills

May benefit from #754

**Comment by jaysonmc** [comment]
The intent is to add this content to the existing Q1 Strategy doc?

**Comment by jaysonmc** [comment]
Waiting for github issues to be resolved 

https://github.com/sara-sabr/ITStrategy/tree/make-case-for-20-improvement

and added more references for learning to program too 

https://github.com/sara-sabr/ITStrategy/tree/updating-references
