### ISSUE TITLE
Create a Cloud Sandbox instance for the IT Strategy team

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#657]
Make a formal request to the Cloud CoE to have our own Cloud Sandbox instance in order to get our own "play with docker" environment.

_Specific usages_
- Public Cloud space to preview Presentations

_Reasoning_
- Play-with-docker does not have the reliability needed (it is sometimes out of capacity and cannot create sessions)
- Work laptops do not allow virtualisation to install docker
- Personal laptops require to have Windows Professional to create virtualisation (or linux). Otherwise one would need to install some tricky software to simulate virtualization (is that even a thing??)
- Even if personal laptops were an option, it limits our ability to be productive should certain families share laptops between spouses and kids (cough cough)

**Comment by Moro-Code** [comment]
Emailed Phil, to see what the steps are and cc'd @jaysonmc

**Comment by Moro-Code** [comment]
Filling cloud intake form

**Comment by Moro-Code** [comment]
Cloud intake form filled and ticket opened  

http://arweb.prv/SRMIS.htm?Ticket=7156953

**Comment by Moro-Code** [comment]
Cloud sandbox created
