### ISSUE TITLE
TransitionToPartner - agile project mgt -> product management

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#67]
In [TransitionToPartner](https://github.com/sara-sabr/ITStrategy/blob/master/Strategies/TransitionToPartner.md), change 
Shift to Agile Project Management 
Back to
Shift to Product Management 

And specific agile project management under the Bi-Modal governance strategy.

"Product Management" has expectations understood by senior level and is a better expression to use to communicate.

**Comment by jaysonmc** [comment]
I put @remyb2canada on this one because I'm still unclear on this product management notion and how it will work into the PM stream. So I'm unable to confidently make any actionable items to associate with it
