### ISSUE TITLE
Table on /references-en /references-fr is not mobile friendly 

### ISSUE THREAD

**Issue by Moro-Code** [sara-sabr/ITStrategy#713]
**Description**
Table is not mobile friendly. Text get's cut off 

**Element(s) Information**  
*Page*:  https://sara-sabr.github.io/ITStrategy/references-en.html
https://sara-sabr.github.io/ITStrategy/references-fr.html
*CSS Selector(s) (if possible and applicable)*:  table.table
*Additional Identifier(s) (if possible and applicable)*:  
*Additional Details*:  

**Screenshot(s) (if possible)**

<img width="513" alt="Screen Shot 2020-01-30 at 2 08 53 PM" src="https://user-images.githubusercontent.com/26819992/73481675-5501d800-436a-11ea-839a-40e02cb0eeb8.png">

result of scan #672 
result of scan #669

**Comment by smellems** [comment]
#882 should help
