### ISSUE TITLE
Produce interviewee package

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#747]
Produce an interview package, for the Interviewees (person/team that will be interviewed) that includes:
- [x] purpose of interview
- [x] safe space expectation
- [x] agenda and interview questions
- [ ] finalize editing

[Draft available here](http://dialogue/grp/BU6810070/Shared%20Documents/Projects/Stakeholder%20Engagement/InterviewQuestions_v2.docx)

**Comment by RachelMuston** [comment]
The linked package seems to require a password in order to open it ... @remyb2canada @ElminaIusifova do you have the password?

**Comment by RachelMuston** [comment]
Interview questions framapad: https://mensuel.framapad.org/p/9f58-interview-questions?lang=en 
Purpose of interview and safe space expectation framapad: https://mensuel.framapad.org/p/9f59-interview-purpose-and-safe-space-expectation?lang=en 
@remyb2canada I didn't do an agenda as I wasn't sure what to put in it beyond...we ask you questions. ?
@ElminaIusifova over to you! :)

**Comment by ElminaIusifova** [comment]
Package for interviewee (by email)
https://mensuel.framapad.org/p/62H76sglHG4TE0NyaBxw
Package for the interviewer (a person who interviews)
https://mensuel.framapad.org/p/qUtTvj996vMydDHWe7KL
@remyb2canada @RachelMuston  I dont think we need agenda in our case.  Feel free to modify both framapads
