### ISSUE TITLE
Interview team X

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#749]
Produce a means to track progress of interviews (e.g. how many interviews we have done so far, of the total 36 planned ones).

Some thoughts:
- create one Github issue per interview, and close that Github issue when an interview is finished
- create a spreadsheet hosted on the internal sharepoint site
- other fancy means....

**Comment by Moro-Code** [comment]
@remyb2canada create an issue template
![issue template](https://user-images.githubusercontent.com/26819992/73789603-18b8e800-476d-11ea-9ccf-1a72a55331b6.PNG)

**Comment by remyb2canada** [comment]
@Moro-Code , we don't mean github issue. We mean that we will be doing 36 interviews and we need to report on our progress (e.g. how many interviews we've done).

rewording Github issue to clarify
