### ISSUE TITLE
Network Question for ITVision

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#76]
I think the idea was to segregate where you do corporate work and where the production systems runtime actually happens.

Up for discussion with @e-wu I think.

_Originally posted by @gcharest in https://github.com/sara-sabr/ITStrategy/pull/62_

**Comment by e-wu** [comment]
Ideally yes. To apply the KISS principal, internet first networks as everything is slowly transitioning to the cloud in some shape or form.
