### ISSUE TITLE
Investigate audit requirements

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#763]
As per BSI feedback (2020-02-05), systems that make payments are heavily audited. There are requirements for system changes that must be documented. Moving to devops will need to address these audit requirements.

Reach to Risk Management team within BOP (GB team)

**Comment by jaysonmc** [comment]
@jaysonmc get contact from auditing in IITB, book meeting

**Comment by jaysonmc** [comment]
Meeting booked with resource from IAERMB for afternoon of August 31st
