### ISSUE TITLE
Team Training Session

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#768]
Mandatory training

**Comment by jaysonmc** [comment]
Pending manager (director) approval

**Comment by jaysonmc** [comment]
Approved received

Verify material, then book meeting

**Comment by jaysonmc** [comment]
Meeting booked (Feb 14th)

**Comment by gcharest** [comment]
@jaysonmc Can you please confirm if to be closed.

**Comment by jaysonmc** [comment]
Completed. Still need to do with one more team member (which is being done tomorrow). Then I shall close.
