### ISSUE TITLE
PROPOSAL - new milestone to Build the SEED/SKILLZ Inventory app

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#796]
_Problem Statement_

IITB HR had a problem called "SEED" where employees could upload their resumes as a means to broadcast their skillsets and aspirations. This would then let IITB managers a way to find expertise, making it easier to allow micro-missions, and allow employees greater mobility and exposure.

The current program doesn't seem to be automated enough where HR no longer had the capacity to support it. It may not have been adequately broadcasted enough, or intuitive as well to be fully used.

At first, it sounds similar to the [GCConnex Career Marketplace](https://gcconnex.gc.ca/missions/main). 

_Proposal_

- Evaluate IITB HR's SEED program with that of [GCConnex Career Marketplace](https://gcconnex.gc.ca/missions/main) for similarities and gaps (to justify whether to use GCConnex or not)
- Build a SEED web application to sustain the SEED program without administrative burdens and make it intuitive for users (managers and employees)

**Comment by gcharest** [comment]
Could this also align with Talent Cloud as a platform? 🤔

**Comment by Moro-Code** [comment]
This is interesting. I'm looking for an app to build in any case if I'm being honest. Who can I speak to to find more information about the program. Are there any existing applications in place ?
