### ISSUE TITLE
PROPOSAL - new milestone Produce Strategy to replace "buy vs build" principle 

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#798]
Review the "buy vs build" ESDC IT principle by providing an alternate that is more aligned with today's IT landscape and business context: one of high complexity and unpredictability. Software purchasing, adopting, or building be comes a risk mitigation activity.

**Comment by smellems** [comment]
New milestone is here : https://github.com/sara-sabr/ITStrategy/milestone/46
