### ISSUE TITLE
Produce Interviewer package

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#812]
Produce a package for the interviewer that includes:
- [x] the script
- [x] [field guide](https://mensuel.framapad.org/p/9f59-interviewer-field-guide?lang=en)
- [x] edit the whole thing nicely

[draft package available here](http://dialogue/grp/BU6810070/Shared%20Documents/Projects/Stakeholder%20Engagement/Package%20-%20Interviewer%20(IT%20Strategy).docx)

**Comment by RachelMuston** [comment]
Script framapad: https://mensuel.framapad.org/p/9f59-Interview_script?lang=en

Field guide framapad:  https://mensuel.framapad.org/p/9f59-interviewer-field-guide?lang=en 

@ElminaIusifova over to you! :)

**Comment by RachelMuston** [comment]
Package for the interviewer (a person who interviews)
https://mensuel.framapad.org/p/qUtTvj996vMydDHWe7KL

**Comment by remyb2canada** [comment]
Task Pending team debrief to be held March 12th
