### ISSUE TITLE
Blog - A brief history of large IT Projects

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#817]
Review the list of Auditor General reports (and other reliable sources) on the assessments over time regarding large IT projects.

Synthesize the reports to identify patterns of failures, areas that have been looked at to improve (e.g. governance and project management practices), increase/decrease/consistent failure rates over time, and whether we should be looking at a different means to handle large IT projects (such as reducing their size).

Our OneNote includes the list of AG report that references large IT projects: onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Reports.one#The%20risks%20of%20large%20IT%20Projects&section-id={65A207EF-B479-4B73-AE24-0A22F40C38D6}&page-id={CEFE1034-E08C-40FE-BB39-5D7805FEB883}&end

Links to IT Strategy mandate:
- [IT is a shared accountability](https://sara-sabr.github.io/ITStrategy/esdc-it-strategy.html): both "the business" and IT needs to absorb the costs and risks of using technology
- [GC digital Standards](https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html): design with users, iterate and improve frequently
- [DevOps](https://cloud.google.com/devops)

**Comment by myp192** [comment]
Currently dealing with some little git issues to make the changes

**Comment by remyb2canada** [comment]
PR #971
