### ISSUE TITLE
GC/Code Roadmap

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#82]
- Transition entire dept to git 
- No more renewing or purchasing other source control solutions

**Comment by smellems** [comment]
Git should be the standard version control system for all of ESDC.  We should start with all new projects and also push them to be open by default.

Migrating legacy code/version control to Git (even internal Gitlab, so not open) might cause some issues with current process.  Might be a good thing, and we should assist teams that want to use Git.

**Comment by gcharest** [comment]
So one of the strategies would be providing support and guidance (not necessarily just us) to move to Git?

**Comment by gcharest** [comment]
Where's the roadmap at? This is identified as WIP, is this the case? If not we should put back to the `To Do` stage

**Comment by jaysonmc** [comment]
Moved back into 'to-do' as Guillaume suggested. 

This on the roadmap, though less important than other issues associated with the milestone. 

Also the medium and long term plans should take precedent over this
