### ISSUE TITLE
Research - public sector organization success stories in using OSS for large systems

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#849]
To tilt senior leaders in believing the DORA model can work for Federal Government:

- public sector org
- large scale transaction/systems
- no large vendors/system intergrators

Goal: find success stories that can demonstrate that new ways of procuring/building software without depending large RFPs and system integrators can work

something with France/Paris Policy debt?

**Comment by gcharest** [comment]
British Columbia, NASA, US DoD, France, CERN
