### ISSUE TITLE
Contact security regarding CATS code

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#854]
There is a CATS code 51940

onenote:http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Reports.one#Continuous%20improvement%20and%20learning%20report%20(April%201%20-%20Jan%2031%202020)&section-id={65A207EF-B479-4B73-AE24-0A22F40C38D6}&page-id={92AC06ED-3864-4D9B-9528-D3245A847035}&end

Was wondering what this is intended to reference, and if we could highlight it on our Q1 strategy guidance.

Should reach out to security manager

**Comment by RachelMuston** [comment]
Hi @jaysonmc I'm assuming you mean CATS code# 10608 (IT Security Training for IITB) and not CATS code #51940 (EI and CPP/OAS appeals process improvements) for this issue?

Also note that CATS code 10608 is assigned to the Cost Centre for Denise Boudreau.

**Comment by RachelMuston** [comment]
Email sent to Denise Boudreau. :)
