### ISSUE TITLE
Work with finance/procurement to create agile RFP

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#855]
If one does not already exist ... if it does, close with issue 

- Work with finance to create an RFP that follows guidance from here 
https://github.com/sara-sabr/technology-budgeting/blob/master/handbook.md

Ex:
- A Statement of Objectives rather than a Statement of Work
- Quality Assessment Surveillance Plan (QASP)
- Establish clear requirements about the regular delivery of working code, documentation, testing
- Ownership of all work products remaining with the state

**Comment by gabrielcossette** [comment]
See https://www.gcpedia.gc.ca/wiki/Agile_Procurement

**Comment by jaysonmc** [comment]
Oh that's fantastic. Thanks @gabrielcossette !
