### ISSUE TITLE
Automate generation of PDF and docx for markdown pages

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#859]
In our Travis CI, add the automatic generation of PDFs for pages (or at least Strategies) so that visitors can easily download one for later reading.

Example on how to implement in Travis: https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by RachelMuston** [comment]
Once these files are automatically created, will they just be posted on our website or also posted on our internal SharePoint?
