### ISSUE TITLE
Document Git Process

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#86]
Document a step by step process to make newcomers familiar with git 

onenote: http://dialogue/grp/BU6810070/Shared%20Documents/IT%20Strategy%20Workbook/Onboarding.one#Git%20Walkthrough&section-id={0CEE8A1B-9103-4711-8703-9122E1A71FD8}&page-id={A3777582-56F0-45D1-949D-60F652916D89}&end

**Comment by gcharest** [comment]
I think this is pretty solid and with the [Contributing instructions](https://github.com/sara-sabr/ITStrategy/blob/master/CONTRIBUTING.MD#instructions), we've got something solid I think we can close this issue?

**Comment by jaysonmc** [comment]
@gabrielcossette 
I'm with Guillaume, think we can close this one? 

Also no milestone ...

**Comment by gabrielcossette** [comment]
The original issue is to document Git for newcomers. The Contributing instructions are awesome but you need to know Git beforehand. There's a great walktrough in the referenced OneNote. Maybe it should be added to GitHub Wiki?

What do you think @arushisharma19 (assignee)?
