### ISSUE TITLE
New Build vs Buy Strategy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#866]
- Write Build vs Buy Strategy

- Complementary data analysis required

- Previous document (https://sara-sabr.github.io/ITStrategy/buy-vs-build-start.html) is referenced, though target audience is different (EARB). Renaming is probably in order

There is build vs buy for an individual user or group (seems to be what our previous iteration was geared towards), and one for enterprise decisions (what the second iteration is attempting to do).

**Comment by jaysonmc** [comment]
Work thus far has been on Word at home (making an attempt at going a little more standard process for this one [for the format, any who])

Will upload to SharePoint and post a link in the near future

**Comment by jaysonmc** [comment]
https://drive.google.com/open?id=1uyQYHaa466vlb2TV6xywoAxKR6ZAQn4SnSImArjPR4c

**Comment by jaysonmc** [comment]
Currently being reviewed by mgmt, and folks from TBS and CDS. Data analysis ongoing

**Comment by jaysonmc** [comment]
Tracking can be found in the Build versus Buy folder in the temporary IT Strategy Google doc, named "Tracking"

**Comment by gcharest** [comment]
Regarding the Cloud First, TBS is pushing for a [Right Cloud Strategy](https://www.canada.ca/en/government/system/digital-government/modern-emerging-technologies/cloud-services/government-canada-right-cloud-selection-guidance.html)
