### ISSUE TITLE
IT Picture - long term

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#88]
Renamed from ITVision to ITPicture to reflect latest discussions.

- [ ] Keep high level
- [ ] Much shorter than medium term
- [ ] Focus on core competencies

(find link article on Slack about roadmapping that puts long term view as high level only)

Provide a >10 year IT Vision for ESDC from different perspectives (audiences)
https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/it-picture-long-term.md

- [ ] Add external references (Gartner, Forrester, Deloitte, etc.)

**Comment by jaysonmc** [comment]
What unit of work is this issue meant to represent? Perhaps a short description? 

Ex: Update document _X_ and merge into master?

**Comment by remyb2canada** [comment]
@jaysonmc 
The unit of work is the peer review:
- recommend changes by initiating a PR
- get IT Strategy's team inputs via PR's collaboration space
- merge to master if IT Strategy's team accepts PR

We then need a team consensus as to "when" a document is sufficiently finalized that it can start being shared with other teams without being "draft mode" (which other teams may interpret as not worthy of their attention yet)

**Comment by gcharest** [comment]
So, based on the items above, the remaining work on this issue is:

- Add references to all documents. This is in line with issue #231

**Comment by gcharest** [comment]
Keep it very high level - Just like War & Peace & IT, DevOps Handbook, Accelerate, etc.
