### ISSUE TITLE
Summarize strategies

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#90]
[ESDC IM/IT Strategy and Policy Development](http://dialogue/grp/IITB-DGIIT-Gov-New-Nouveau/Documents/Strategies/IITB%20Strategic%20Framework_3.docx)

[ESDC IM/IT Strategies Review - Spreadsheet](http://dialogue/grp/BU6810070/Shared%20Documents/Forms/AllItems.aspx)

**Comment by jaysonmc** [comment]
@gabrielcossette 
What's the state of this one? It says in progress but no update for 18 days? 

Also no associated milestone?

**Comment by gabrielcossette** [comment]
@arushisharma19 
It's assigned to you, any update?

@jaysonmc 
I was not sure of the scope of this task when I copied it from Trello. Do you know the details?
Considering milestones must have a clear impact to the org (be action oriented), would it be applicable here?

**Comment by jaysonmc** [comment]
Ah yes, @arushisharma19 

I think this one is done for now. When the team returns, we should present to the team and decide what to do with the info (leave on sharepoint, move to OneNote, move to github?)
