### ISSUE TITLE
Evaluate how IITB might operationalize the collection of DORA's 4 key metrics

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#908]
Need to evaluate how, realistically, we will be able to collect data to measure the 4 key metrics defined in DORA and highlighted in our [Logic Model](https://sara-sabr.github.io/ITStrategy/esdc-it-strategy.html):

- Lead time for changes
- Deployment frequency
- Time to restore service
- Change failure rate

This is to be used:
1. As part of the [Logic Model](https://sara-sabr.github.io/ITStrategy/esdc-it-strategy.html)
2. Cross referenced with the TB Sub for the technical deb  (issue #956)
3. As part of the [Alternate IT Solution Delivery Model](https://github.com/sara-sabr/ITStrategy/milestone/47)

**Comment by smellems** [comment]
#981
