### ISSUE TITLE
Story about HR White List success (IITB Showcase)

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#912]
The HR White Listing journey is an excellent story to raise and communicate IITB-wide

In less than 5 days, working over the weekend, it involved collaboration with DTS and CDO to produce a production-ready Web Application, hosted in the cloud, AND a CIO demo.

Potential avenue to communicate the story: IITB Showcase (once things get normalized)

**Comment by smellems** [comment]
Blog (English only): https://sara-sabr.github.io/ITStrategy/2020/05/20/Team-Topologies-Whitelisting-app.html
