### ISSUE TITLE
Document GC/ESDC use cases for a simplified procurement option for OSS

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#919]
Why does ESDC need a procurement option like GCDevEx (small procurements that are easily accessible to all Canadians to bid on). Who would use it, and how.  Demonstrate that this is a solid supply of opportunities in the wings

**Comment by remyb2canada** [comment]
start with [HR White Listing app](https://github.com/sara-sabr/ITStrategy/milestone/48) :)

**Comment by RachelMuston** [comment]
Possible text for the HR Whitelisting opportunity documented here: https://docs.google.com/document/d/18cgQbWPdFPiScMOleQQ-GjGxg71Tnd5hXUKTIh6hKVg/edit?usp=sharing. 

Needs review.

**Comment by smellems** [comment]
Business case in #1029
