### ISSUE TITLE
Improve Information management (Web Content) 

### ISSUE THREAD

**Issue by myp192** [sara-sabr/ITStrategy#937]
Reference : https://docs.google.com/document/d/1BxxIHJdDBjY2VLL0cbpivMdaOuDyn0CVizASmqW7FWU/edit

**Comment by remyb2canada** [comment]
Reached out to [IM lead for IITB](http://dialogue/grp/IMSCS-SGISC/Lists/CGIIML/AllItems.aspx)
from the [IMO Portal](http://dialogue/grp/IITB-DGIIT-Gov-New-Nouveau/SitePages/IM-GI.aspx)

**Comment by remyb2canada** [comment]
TIL: IM lead for IITB is in SABR :)

Forwarded the request to the Enterprise IM team (under BSIM)

**Comment by jaysonmc** [comment]
Removed -> Quarterly Strategies
Q1 Strategy - Continuous Improvement and Learning -> Work in Progress
