### ISSUE TITLE
PROPOSAL - Produce a Teleworking Package

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#945]
PROPOSAL for a new milestone

GOAL: Create a teleworking package to make it easier for ESDC employees to telework.

This issue was created after the monthly IT Strategy meeting with the DG when it was raised that the pandemic created new ways of working and collaborating. The concern is to lose these modern ways of working when work will normalize again.

The teleworking package would look at:

- [ ] Create an easy and intuitive request for teleworking
- [ ] Provide onboarding suite of tools (e.g. laptop, headset, access to remote tools)
- [ ] Provide intuitive guidance for remote employees (e.g. online resources, best practices to follow)
- [ ] Provide intuitive guidance for managers (e.g. deliverable-based management, not throughput)

**Comment by jaysonmc** [comment]
In addition to this (with a similar goal)

Could use the application whitelisting app for this? Add a field with something like "willing to remain fully remote post COVID19" or "Willing to release desk located at 22 Eddy post COVID19"

Then we can use this list and compare it against their desk. Use this report to rearrange folks and try and "empty out" sections of buildings to be dropin desks (ie, not allocated to any given person), essentially start turning buildings in to workplace 3.0, resulting in increased numbers of folk able to continue working remotely.

Later could manage through Odoo, or o0365 plugin, and automate the request for teleworking (through some workflow, perhaps)

As for the other three (providing onboarding, intuitive guidance for employees and managers) great idea.
