### ISSUE TITLE
Blog: WhiteListing App Approach: Team Topologies

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#948]
Turn article explaining apparoch to organizing the teams during the WhiteListing Application development process in to a blog post on the IT Strategy website

https://docs.google.com/document/d/153WAOdEXIbKZJRumPDXhwNzhfcRA0AozxP15gBRC7ns/edit?usp=sharing

**Comment by smellems** [comment]
Done: https://sara-sabr.github.io/ITStrategy/2020/05/20/Team-Topologies-Whitelisting-app.html
