### ISSUE TITLE
Connect with TBS agile procurement folks

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#954]
Learn more about their process

**Comment by RachelMuston** [comment]
Gabriel has contacts at PSCP re: agile procurement :-)

**Comment by jaysonmc** [comment]
Reach out post PSPC collaboration

**Comment by RachelMuston** [comment]
closing this as we are in regular contact with the SSC agile procurement team and also CFOB (procurement innovation) is leading agile procurement at ESDC
