### ISSUE TITLE
OSS - Comment/improve existing material

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#96]
**Material to review**
- [OSS Framework Deck](http://dialogue/grp/TAWS-ATST/Collaboration%20Architecture%20Services/Projects/Artificial%20Intelligence%20and%20Open%20Source/OSS/EOSS%20Management%20Framework%20Plan%20-%20Official.pptx)
- [OSS Framework Document](http://dialogue/grp/BU6810070/Shared%20Documents/Reviews/ESDC%20Open%20Source%20Management%20Framework%20v%201.1-IT_Strategy_Comments.docx)
  - Forked from original and enabled Track Changes - add your feedback directly in the document
- [OSS Process and Forms Site](http://dialogue/grp/CO6721427/SitePages/Home.aspx)

**Comment by gcharest** [comment]
Need to review and provide feedback ASAP: planned to present in September already.

**Comment by gabrielcossette** [comment]
I reviewed the material linked in the description. Can you do the same @gcharest @smellems and add your feedback?

**Comment by smellems** [comment]
I really like that all this already exists and is being submitted for endorsement.  They even have inventories of OSS they are using!

Recommends that:
- ESDC considers OSS Solutions as the preferred option in IT procurement;
- An OSS Programs Office be created.

They also reference the TBS guides on Github!

One this I noticed is that Chrome is identified as OSS.  Chromium is OSS not Chrome.

**Comment by gcharest** [comment]
I reviewed the documents listed above and added a few comments. Overall, this is great work and I really am looking forward the presentation.

I do have a few notes regarding the presentation itself but will share them back at the office.

**Comment by gcharest** [comment]
@gabrielcossette @smellems Just confirming I sent all my comments on presentation via email and my comments on the word document have been saved on your fork Gabriel.

Thanks! (I think we're good to close the issue?)
