### ISSUE TITLE
Discuss Continuous Improvement Strategy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#960]
- What does the launch look like? Did we already launch?
- Is work already continuing based on #956? (remy: this is NOT linked to issue #956 
- Remy to send measurement documentation (TBS Sub) (remy: this is NOT linked to measurement documentations exercise)

Remy comment:
Continuous Learning Strategy is linked to [milestone 42](https://github.com/sara-sabr/ITStrategy/milestone/42) (create the IT strategy framework and logic model)

Metrics for the continuous learning strategy are NOT the DORA 4 key metrics. That would be unrealistic and easily argued against. Instead, the continuous learning strategy must have metrics around learning. Which, in turn, will influence the medium term outcomes as stated in our Logic Model. Which, ultimately, are believed to improve the DORA 4 key metrics

See documentation sent over email on 2020-05-01

We need to do a lot more work on the continuous learning strategy

**Comment by jaysonmc** [comment]
BN rejected by Director.

Follow up required.

**Comment by jaysonmc** [comment]
What's the reasoning behind moving this one back to to-do?

**Comment by smellems** [comment]
Draft presentation for discussion of overall strategy
https://sara-sabr.github.io/util-presentation/presentation.html?url=https://raw.githubusercontent.com/sara-sabr/ITStrategy/strategy-10/presentations/en/Strategy.md
