### ISSUE TITLE
Set a standard definition for the term "DevOps teams"

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#969]
As per BPMO feedback, DevOps teams should be clearly defined so that not any team could proclaim itself to be a DevOps team (especially since the strategy's policy gives DevOps teams authority to deploy into production).

O365 link  (all ESDC has access to it): https://014gc-my.sharepoint.com/:w:/g/personal/remy_bernard_hrsdc-rhdcc_gc_ca/EaU8oDNt7iJNj8Zy_M64TOkBVJBlFhQ2d_fzOuF2N6bt8A?e=F5HEeL

**Comment by remyb2canada** [comment]
Need to connect with CCoE as they are working with ops and security to define one. this can lead to confusion as there is a direction to differentiate between DevOps and DevSecOps which contradicts the notion that security is everyone's responsibility and is part of every software building/operation

**Comment by smellems** [comment]
Add management section - related to #1050
