### ISSUE TITLE
Develop the DevEx pitch for CFOB

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#972]
- Review Procurement policies and processes to use their lingo
- Find procurement innovation requirements in senior managements performance agreements - what boxes can DevEx help senior procurement/finance folks check?
- [ ] Gap Analysis (#1000)

[draft CFOB deck](https://docs.google.com/presentation/d/1guX117_Cl6vGrfGb8E8En5gLLzjJDLFBxnJR1whDb-w/edit#slide=id.g777ef74bc1_1_6)

**Comment by jaysonmc** [comment]
https://github.com/sara-sabr/ITStrategy/issues/1000

**Comment by jaysonmc** [comment]
Meeting with Procurement Innovation agreed to co-sponsor, so the intent has been achieved. Closing
