### ISSUE TITLE
Get lessons learned from YDG on effectivnes of SDM model

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#975]
Find pilot project to try new model.

Some current thoughts are:
- the [Youth Digital Gateway](https://dialogue/grp/BU5946064/ESDC%20EARB/Fiscal%20Year%202019-2020/2019-11-18/Tab%203%20-%20Youth%20Digital%20Gateway.pptx) due to alignment with their mandate
- CPP-E

**Comment by jaysonmc** [comment]
J.S. (Senior Advisor) reached out to use strategy as cover. Could ask their initiative to be the pilot project

**Comment by jaysonmc** [comment]
Reached out to JS regarding their project becoming the pilot project
