### ISSUE TITLE
Change the Strategy Map into a DevOps Capability Maturity Model

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#979]
Change the current [Strategy Map](https://sara-sabr.github.io/ITStrategy/strategy-summary.html) into a Maturity Model based on the [DORA DevOps capabilities](https://cloud.google.com/devops/)

The main audience of the Maturity Model are IT teams.

The goal is to take the DORA DevOps capabilities as is and, for each capability, provide:

- [ ] Short description
- [ ] Performance Indicators (metrics) with their data collection sources & frequency that the IT Strategy team can use to periodically measure performance
- [ ] Maturity level target threshold (when could we say we're "good enough")
- [ ] A strategy that IT teams can use to improve their maturity in a specific capability

It is expected that, through a Maturity Model, the IT Strategy team will be able to better communicate to audiences (management and IT teams), their intent and the progression towards the long term target state.

**Comment by remyb2canada** [comment]
Stuff happening [here](https://docs.google.com/document/d/1BDqZZTuv5clrWu8-py3tECchspUgBXZgPg8RdmT4d9Y/edit?usp=sharing)
and [also here](https://etherpad.wikimedia.org/p/iitbs-d0r4-m47ur17y-m0d3l)
:)

**Comment by tsanov** [comment]
@remyb2canada , when you wrote "The goal is to take the DORA DevOps capabilities as is ...", did you mean that the Department Application Capability Model (it's available in QualiWare) will eventually be aligned with the DORA DevOps capabilities?

**Comment by remyb2canada** [comment]
@tsanov I am not aware of the Department Application Capability Model. We'll have to chat to see alignment. But the goal is that, yes, we would use the DORA DevOps capabilities to inform what capabilities are needed to perform DevOps.

**Comment by remyb2canada** [comment]
Closing this issue as we are moving away from capability maturity model and, instead, towards an assessment tool instead. But such tool to be defined after we clarify our logic model (issue #981 )
