### ISSUE TITLE
Build vs Buy: Second Iteration of Outreach

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#995]
Work being tracked in IT Strategy temporary Google Drive, in the Build vs Buy folder, in the Tracking spreadsheet

**Comment by jaysonmc** [comment]
Need to follow up with those who havent yet provided feedback

Follow up with ARC

**Comment by jaysonmc** [comment]
Reached out to EA (GM) and IITB Finance again

Tenatively booked for ARC for July 14

**Comment by gcharest** [comment]
Due date for revised version for **July 3, 2020**.

**Comment by jaysonmc** [comment]
Strategy sent to ARC on July 3, 2020

**Comment by gcharest** [comment]
fixed in #1086 further changes to be tackled in 0.05
