### ISSUE TITLE
Operating Model options

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#999]
Evaluate options for an operation model. Includes:

- Staff requirement to offer guidance for bidders (the public) and publishers (GC managers publishing their problems)
- Staff requirement to provide GCDevExchange software operations/maintenance
- pay to play (should other departments want to levarage)
- potential of leveraging micro-missions
- linkages with departmental procurement backoffice processes

Inform senior management of expectations

**Comment by jaysonmc** [comment]
Being dealt with here: https://github.com/sara-sabr/ITStrategy/issues/1029
